#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Producer-head QK/OV analysis for the COCO two-object spatial task.

This script is the next stage after:

    analyze_spatial_storage_transport_utilization_v3.py

It reuses that script's extraction cache and asks a narrower mechanistic
question:

    Which attention heads act as visual-to-object spatial-relation producers,
    and is their role better explained by QK routing, OV writing, or both?

For one layer/head and one object target t:

    QK functional routing:
        A[t, visual]

    head-local visual read:
        u_t = sum_{p in visual} A[t,p] V_p

    actual residual write:
        w_t = W_O^h u_t

    relation write:
        r_pre  = u_subject - u_reference
        r_post = W_O^h r_pre

The script has two phases.

PHASE 1: scan
-------------
Uses the existing v3 cache to compute, for every selected head:

  QK:
    * visual-attention centroid accuracy
    * visual-attention GT margin
    * visual-attention mass

  pre-OV:
    * cross-fitted centroid accuracy of r_pre

  post-OV:
    * exact cross-fitted centroid accuracy after W_O
    * post-W_O relation-write norm
    * relation-margin correlation with the whole object-pair residual

The post-W_O centroid metric is computed exactly in head space using:

    G_h = (W_O^h)^T W_O^h

For cosine classification:

    cos(W_O x, W_O c)
      = x^T G_h c / sqrt((x^T G_h x)(c^T G_h c))

This avoids materializing [N, hidden_size] projected vectors for every head.

PHASE 2: causal
---------------
For top producer candidates, reruns original and swapped COCO questions and
performs four interventions at the subject/reference object tokens.

1. qk_swap_on_original
   Replace the selected head's original object->visual routing with the
   identity-aligned swapped-question routing, while holding the original visual
   V states fixed. This is a functional QK corruption test.

2. ov_visual_ablate_on_original
   Remove the selected head's actual post-W_O visual contribution from the
   original object tokens. This tests whether the head's visual OV write is
   necessary.

3. qk_restore_on_swapped
   Replace the selected head's swapped object->visual routing with the
   identity-aligned original routing, while holding swapped V fixed. This is a
   functional QK restoration test.

4. full_visual_write_restore_on_swapped
   Replace the selected head's complete swapped visual write with its original
   visual write. This tests whether the producer write is sufficient to restore
   the original relation direction. It is not a pure OV-only intervention; it
   restores the full A·V·W_O contribution.

The original and swapped questions are independent model inputs. Object targets
are aligned by object identity:

    original A-subject  <-> swapped A-reference
    original B-reference <-> swapped B-subject

The fixed original-axis relation margin is:

    M = z_original_GT - z_opposite

For original-side corruption:

    normalized_damage =
        (M_original - M_intervened)
        / (M_original - M_swapped)

For swapped-side restoration:

    normalized_recovery =
        (M_intervened - M_swapped)
        / (M_original - M_swapped)

Values are not clipped.

Required existing output
------------------------
The source directory must contain:

    config.json
    extraction.jsonl
    cache/<sid>.npz

generated by analyze_spatial_storage_transport_utilization_v3.py.

Outputs
-------
    config.json
    producer_head_metrics.csv
    producer_top_heads.json
    producer_top_per_sample.jsonl
    producer_causal.jsonl
    producer_causal_summary.csv
    report.txt
    errors.jsonl

Example: scan + causal on LLaVA-1.5-7B
--------------------------------------
CUDA_VISIBLE_DEVICES=0 python -u analyze_coco_producer_qk_ov_v1.py \
  --model llava-7b \
  --source-output-dir \
    output/spatial_storage_transport_utilization/coco/llava-7b \
  --phase all \
  --layers all \
  --scan-status all \
  --rank-metric joint_geomean \
  --top-heads 12 \
  --causal-status both_correct \
  --causal-max-samples 100 \
  --device cuda:0 \
  --output-dir \
    output/coco_producer_qk_ov/llava-7b \
  --overwrite

Example: Qwen-3B
----------------
CUDA_VISIBLE_DEVICES=0 python -u analyze_coco_producer_qk_ov_v1.py \
  --model qwen-3b \
  --source-output-dir \
    output/spatial_storage_transport_utilization/coco/qwen-3b \
  --phase all \
  --layers all \
  --scan-status all \
  --rank-metric joint_geomean \
  --top-heads 12 \
  --causal-status both_correct \
  --causal-max-samples 100 \
  --device cuda:0 \
  --output-dir \
    output/coco_producer_qk_ov/qwen-3b \
  --overwrite
"""

from __future__ import annotations

import argparse
import contextlib
import csv
import gc
import importlib.util
import json
import math
import random
import shutil
import sys
import traceback
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

import numpy as np
import torch
from PIL import Image
from tqdm import tqdm

try:
    import transformers
    from transformers import AutoProcessor
except Exception as exc:
    raise SystemExit(f"Unable to import transformers: {exc}")


SCRIPT_VERSION = "coco-producer-qk-ov-v1"
RELATIONS = ("left", "right", "above", "below")
REL_TO_ID = {name: index for index, name in enumerate(RELATIONS)}
ID_TO_REL = {index: name for name, index in REL_TO_ID.items()}
OPPOSITE = {
    "left": "right",
    "right": "left",
    "above": "below",
    "below": "above",
}
STATUSES = ("all", "both_correct", "original_only", "swapped_only", "both_wrong")
CAUSAL_CONDITIONS = (
    "qk_swap_on_original",
    "ov_visual_ablate_on_original",
    "qk_restore_on_swapped",
    "full_visual_write_restore_on_swapped",
)


# -----------------------------------------------------------------------------
# CLI and generic utilities
# -----------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--model", required=True)
    p.add_argument(
        "--source-output-dir",
        required=True,
        help=(
            "Existing analyze_spatial_storage_transport_utilization_v3.py "
            "output directory."
        ),
    )
    p.add_argument("--phase", choices=("all", "scan", "causal"), default="all")
    p.add_argument("--dataset", default="coco_two", choices=("coco_two",))
    p.add_argument("--data-root", default="data")
    p.add_argument(
        "--prompt-jsonl",
        default="prompts/COCO_QA_two_obj_with_answer_four_options.jsonl",
    )
    p.add_argument("--device", default="cuda:0")
    p.add_argument("--attn-impl", default="eager", choices=("eager",))
    p.add_argument(
        "--layers",
        default="source",
        help="'source', 'all', or comma-separated zero-based decoder layers.",
    )
    p.add_argument(
        "--object-state",
        choices=("last", "mean"),
        default="last",
        help="Must match the source v3 extraction setting.",
    )
    p.add_argument("--centroid-metric", choices=("cosine", "euclidean"), default="cosine")
    p.add_argument("--scan-status", choices=STATUSES, default="all")
    p.add_argument(
        "--rank-metric",
        choices=(
            "qk_attention_centroid_accuracy",
            "pre_ov_centroid_accuracy",
            "post_ov_centroid_accuracy",
            "joint_min",
            "joint_geomean",
        ),
        default="joint_geomean",
    )
    p.add_argument("--top-heads", type=int, default=12)
    p.add_argument("--min-visual-mass", type=float, default=0.0)
    p.add_argument("--save-top-per-sample", action=argparse.BooleanOptionalAction, default=True)

    p.add_argument("--causal-status", choices=STATUSES, default="both_correct")
    p.add_argument(
        "--causal-max-samples",
        type=int,
        default=100,
        help="0 or negative means all eligible samples.",
    )
    p.add_argument(
        "--causal-heads",
        default="top",
        help=(
            "'top' uses producer_top_heads.json; otherwise use entries like "
            "'12:25,12:4,15:5'."
        ),
    )
    p.add_argument(
        "--causal-conditions",
        default=",".join(CAUSAL_CONDITIONS),
    )
    p.add_argument(
        "--causal-layer-unions",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Also intervene on the union of selected heads in each layer.",
    )
    p.add_argument("--min-margin-denominator", type=float, default=1e-4)
    p.add_argument(
        "--causal-require-margin-sign",
        action=argparse.BooleanOptionalAction,
        default=True,
        help=(
            "Require cached original GT-vs-opposite margin > 0 and swapped "
            "fixed-axis margin < 0 before causal validation."
        ),
    )
    p.add_argument("--trace-layer-chunk", type=int, default=4)
    p.add_argument("--replay-tolerance", type=float, default=5e-3)
    p.add_argument("--seed", type=int, default=17)
    p.add_argument("--max-samples", type=int, default=None)
    p.add_argument("--print-every", type=int, default=5)
    p.add_argument("--empty-cache-every", type=int, default=10)

    p.add_argument(
        "--v3-script",
        default="analyze_spatial_storage_transport_utilization_v3.py",
    )
    p.add_argument(
        "--base-script",
        default="analyze_coco_centroid_generation_step1_v4.py",
    )
    p.add_argument(
        "--attention-helper",
        default="analyze_coco_flip_attention_spatial_vectors_v1.py",
    )
    p.add_argument("--output-dir", required=True)
    p.add_argument("--overwrite", action="store_true")
    p.add_argument(
        "--resume",
        action=argparse.BooleanOptionalAction,
        default=True,
    )
    p.add_argument(
        "--fail-fast",
        action=argparse.BooleanOptionalAction,
        default=True,
    )
    return p.parse_args()


def import_file(path: Path, module_name: str) -> Any:
    path = path.resolve()
    if not path.exists():
        raise FileNotFoundError(path)
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise ImportError(path)
    sys.modules.pop(module_name, None)
    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    try:
        spec.loader.exec_module(module)
    except Exception:
        sys.modules.pop(module_name, None)
        raise
    return module


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(value, handle, ensure_ascii=False, indent=2)


def append_jsonl(path: Path, row: Mapping[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps(dict(row), ensure_ascii=False) + "\n")


def read_jsonl(path: Path) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    if not path.exists():
        return rows
    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            text = line.strip()
            if not text:
                continue
            try:
                rows.append(json.loads(text))
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSON at {path}:{line_number}: {exc}") from exc
    return rows


def write_csv(path: Path, rows: Sequence[Mapping[str, Any]]) -> None:
    rows = list(rows)
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    fields: List[str] = []
    seen = set()
    for row in rows:
        for key in row:
            if key not in seen:
                fields.append(str(key))
                seen.add(key)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow(dict(row))


def safe_mean(values: Iterable[Any]) -> float:
    array = np.asarray(list(values), dtype=np.float64)
    array = array[np.isfinite(array)]
    return float(array.mean()) if array.size else float("nan")


def safe_median(values: Iterable[Any]) -> float:
    array = np.asarray(list(values), dtype=np.float64)
    array = array[np.isfinite(array)]
    return float(np.median(array)) if array.size else float("nan")


def safe_corr(left: Sequence[Any], right: Sequence[Any]) -> float:
    x = np.asarray(left, dtype=np.float64)
    y = np.asarray(right, dtype=np.float64)
    mask = np.isfinite(x) & np.isfinite(y)
    if int(mask.sum()) < 3:
        return float("nan")
    x = x[mask]
    y = y[mask]
    if float(np.std(x)) < 1e-12 or float(np.std(y)) < 1e-12:
        return float("nan")
    return float(np.corrcoef(x, y)[0, 1])


def macro_accuracy(pred: np.ndarray, labels: np.ndarray) -> float:
    scores = []
    for label in range(len(RELATIONS)):
        mask = labels == label
        if np.any(mask):
            scores.append(float(np.mean(pred[mask] == labels[mask])))
    return safe_mean(scores)


def relation_margin(logits: Sequence[float], gt: str) -> float:
    values = np.asarray(logits, dtype=np.float64)
    return float(
        values[REL_TO_ID[gt]]
        - values[REL_TO_ID[OPPOSITE[gt]]]
    )


def parse_layers(value: str, source_layers: Sequence[int], n_layers: int) -> List[int]:
    text = str(value).strip().lower()
    if text == "source":
        return sorted(set(map(int, source_layers)))
    if text == "all":
        return list(range(n_layers))
    result: List[int] = []
    for item in text.split(","):
        item = item.strip()
        if not item:
            continue
        layer = int(item)
        if not 0 <= layer < n_layers:
            raise ValueError(f"Layer {layer} outside [0,{n_layers - 1}]")
        result.append(layer)
    if not result:
        raise ValueError("No layers selected")
    return sorted(set(result))


def parse_conditions(value: str) -> List[str]:
    conditions = [item.strip() for item in str(value).split(",") if item.strip()]
    invalid = sorted(set(conditions) - set(CAUSAL_CONDITIONS))
    if invalid:
        raise ValueError(
            f"Unsupported causal conditions {invalid}; allowed={CAUSAL_CONDITIONS}"
        )
    if not conditions:
        raise ValueError("No causal conditions selected")
    return list(dict.fromkeys(conditions))


def status_matches(row: Mapping[str, Any], status: str) -> bool:
    return status == "all" or str(row["generation_pair_status"]) == status


def cache_path(source_dir: Path, sid: int) -> Path:
    return source_dir / "cache" / f"{int(sid)}.npz"


def load_cache(path: Path) -> Dict[str, np.ndarray]:
    if not path.exists():
        raise FileNotFoundError(path)
    with np.load(path, allow_pickle=False) as data:
        return {key: np.asarray(data[key]) for key in data.files}


def stratified_limit(
    rows: Sequence[Mapping[str, Any]],
    limit: Optional[int],
    seed: int,
) -> List[Dict[str, Any]]:
    rows = [dict(row) for row in rows]
    if limit is None or limit <= 0 or len(rows) <= limit:
        return sorted(rows, key=lambda item: int(item["sid"]))

    rng = random.Random(seed)
    groups: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    for row in rows:
        groups[str(row["gt"])].append(row)
    for values in groups.values():
        rng.shuffle(values)

    ordered_labels = [relation for relation in RELATIONS if relation in groups]
    selected: List[Dict[str, Any]] = []
    cursors = {label: 0 for label in ordered_labels}
    while len(selected) < limit:
        progressed = False
        for label in ordered_labels:
            index = cursors[label]
            if index < len(groups[label]) and len(selected) < limit:
                selected.append(groups[label][index])
                cursors[label] += 1
                progressed = True
        if not progressed:
            break
    selected.sort(key=lambda item: int(item["sid"]))
    return selected


# -----------------------------------------------------------------------------
# Model loading
# -----------------------------------------------------------------------------


def load_model_bundle(
    *,
    args: argparse.Namespace,
    base: Any,
) -> Tuple[Any, Any, Any, Sequence[Any], str, Any]:
    two_object = base.import_two_object_module()
    specs = base.merged_model_specs(two_object)
    if args.model not in specs:
        raise ValueError(f"Unknown model {args.model}; available={sorted(specs)}")
    spec = specs[args.model]
    model_class = getattr(transformers, spec.model_class, None)
    if model_class is None:
        raise RuntimeError(
            f"transformers {transformers.__version__} lacks {spec.model_class}"
        )

    kwargs: Dict[str, Any] = {
        "dtype": base.resolve_dtype(spec.dtype_name),
        "low_cpu_mem_usage": True,
        "trust_remote_code": spec.trust_remote_code,
        "device_map": {"": args.device},
        "attn_implementation": args.attn_impl,
    }
    print(f"Loading {args.model}: {spec.repo_id}", flush=True)
    try:
        model = model_class.from_pretrained(spec.repo_id, **kwargs)
    except TypeError:
        kwargs.pop("attn_implementation", None)
        model = model_class.from_pretrained(spec.repo_id, **kwargs)

    model.eval()
    generation_config = getattr(model, "generation_config", None)
    if generation_config is not None:
        if hasattr(generation_config, "do_sample"):
            generation_config.do_sample = False
        for field in ("temperature", "top_p", "top_k"):
            if hasattr(generation_config, field):
                setattr(generation_config, field, None)

    processor = AutoProcessor.from_pretrained(
        spec.repo_id,
        trust_remote_code=spec.trust_remote_code,
    )
    base.configure_processor(model, processor)
    decoder_layers, decoder_path = base.resolve_decoder_layers(model)
    relation_token_map = base.relation_token_variants(processor.tokenizer)
    return model, processor, spec, decoder_layers, decoder_path, relation_token_map


# -----------------------------------------------------------------------------
# Exact post-WO centroid metric in head space
# -----------------------------------------------------------------------------


@dataclass
class MetricCentroidModel:
    centroids: np.ndarray
    gram: np.ndarray
    metric: str

    def scores(self, x: np.ndarray) -> np.ndarray:
        x = np.asarray(x, dtype=np.float64)
        c = np.asarray(self.centroids, dtype=np.float64)
        gram = np.asarray(self.gram, dtype=np.float64)

        if self.metric == "cosine":
            xg = x @ gram
            numerator = xg @ c.T
            x_norm = np.sqrt(np.clip(np.sum(xg * x, axis=1), 1e-24, None))
            cg = c @ gram
            c_norm = np.sqrt(np.clip(np.sum(cg * c, axis=1), 1e-24, None))
            return numerator / np.clip(x_norm[:, None] * c_norm[None, :], 1e-12, None)

        if self.metric == "euclidean":
            output = np.empty((len(x), len(c)), dtype=np.float64)
            for index, centroid in enumerate(c):
                delta = x - centroid[None, :]
                dg = delta @ gram
                output[:, index] = -np.sqrt(
                    np.clip(np.sum(dg * delta, axis=1), 0.0, None)
                )
            return output

        raise ValueError(self.metric)

    def predict(self, x: np.ndarray) -> np.ndarray:
        return np.argmax(self.scores(x), axis=1).astype(np.int64)

    def gt_opposite_margin(self, x: np.ndarray, labels: np.ndarray) -> np.ndarray:
        scores = self.scores(x)
        result = np.empty((len(x),), dtype=np.float64)
        for index, label in enumerate(labels.tolist()):
            gt = ID_TO_REL[int(label)]
            result[index] = (
                scores[index, int(label)]
                - scores[index, REL_TO_ID[OPPOSITE[gt]]]
            )
        return result


def fit_metric_centroids(
    x: np.ndarray,
    labels: np.ndarray,
    gram: np.ndarray,
    metric: str,
) -> MetricCentroidModel:
    centroids = []
    for relation_id in range(len(RELATIONS)):
        mask = labels == relation_id
        if not np.any(mask):
            raise RuntimeError(
                f"Missing class {ID_TO_REL[relation_id]} in centroid training"
            )
        centroids.append(np.asarray(x[mask], dtype=np.float64).mean(axis=0))
    return MetricCentroidModel(
        centroids=np.stack(centroids, axis=0),
        gram=np.asarray(gram, dtype=np.float64),
        metric=metric,
    )


def crossfit_metric_centroids(
    x: np.ndarray,
    labels: np.ndarray,
    folds: np.ndarray,
    gram: np.ndarray,
    metric: str,
) -> Tuple[np.ndarray, np.ndarray]:
    pred = np.full((len(x),), -1, dtype=np.int64)
    margin = np.full((len(x),), np.nan, dtype=np.float64)
    for fold in sorted(set(folds.tolist())):
        train = folds != fold
        test = folds == fold
        model = fit_metric_centroids(
            x[train],
            labels[train],
            gram,
            metric,
        )
        pred[test] = model.predict(x[test])
        margin[test] = model.gt_opposite_margin(
            x[test],
            labels[test],
        )
    return pred, margin




def crossfit_metric_centroids_batched(
    x: np.ndarray,
    labels: np.ndarray,
    folds: np.ndarray,
    grams: np.ndarray,
    metric: str,
) -> Tuple[np.ndarray, np.ndarray]:
    """Exact cross-fitted centroid classification for all heads in one layer.

    x:     [N,H,Dh]
    grams: [H,Dh,Dh]
    returns prediction/margin with shape [N,H].
    """
    x = np.asarray(x, dtype=np.float64)
    labels = np.asarray(labels, dtype=np.int64)
    folds = np.asarray(folds, dtype=np.int64)
    grams = np.asarray(grams, dtype=np.float64)
    n, n_heads, head_dim = x.shape
    if grams.shape != (n_heads, head_dim, head_dim):
        raise ValueError(
            f"Bad batched Gram shape {grams.shape}; expected "
            f"{(n_heads, head_dim, head_dim)}"
        )

    pred = np.full((n, n_heads), -1, dtype=np.int64)
    margin = np.full((n, n_heads), np.nan, dtype=np.float64)

    for fold in sorted(set(folds.tolist())):
        train = folds != fold
        test = folds == fold
        centroids = np.empty(
            (n_heads, len(RELATIONS), head_dim),
            dtype=np.float64,
        )
        for relation_id in range(len(RELATIONS)):
            mask = train & (labels == relation_id)
            if not np.any(mask):
                raise RuntimeError(
                    f"Fold {fold} misses class {ID_TO_REL[relation_id]}"
                )
            centroids[:, relation_id, :] = x[mask].mean(axis=0)

        xt = x[test]  # [Nt,H,D]
        xg = np.einsum("nhd,hde->nhe", xt, grams, optimize=True)

        if metric == "cosine":
            numerator = np.einsum(
                "nhe,hce->nhc",
                xg,
                centroids,
                optimize=True,
            )
            x_norm = np.sqrt(
                np.clip(
                    np.einsum("nhe,nhe->nh", xg, xt, optimize=True),
                    1e-24,
                    None,
                )
            )
            cg = np.einsum(
                "hcd,hde->hce",
                centroids,
                grams,
                optimize=True,
            )
            c_norm = np.sqrt(
                np.clip(
                    np.einsum(
                        "hce,hce->hc",
                        cg,
                        centroids,
                        optimize=True,
                    ),
                    1e-24,
                    None,
                )
            )
            scores = numerator / np.clip(
                x_norm[:, :, None] * c_norm[None, :, :],
                1e-12,
                None,
            )
        elif metric == "euclidean":
            scores = np.empty(
                (int(test.sum()), n_heads, len(RELATIONS)),
                dtype=np.float64,
            )
            for relation_id in range(len(RELATIONS)):
                delta = xt - centroids[:, relation_id, :][None, :, :]
                dg = np.einsum(
                    "nhd,hde->nhe",
                    delta,
                    grams,
                    optimize=True,
                )
                scores[:, :, relation_id] = -np.sqrt(
                    np.clip(
                        np.einsum(
                            "nhe,nhe->nh",
                            dg,
                            delta,
                            optimize=True,
                        ),
                        0.0,
                        None,
                    )
                )
        else:
            raise ValueError(metric)

        test_indices = np.where(test)[0]
        pred[test_indices] = np.argmax(scores, axis=2)
        for local_index, global_index in enumerate(test_indices.tolist()):
            gt_id = int(labels[global_index])
            opposite_id = REL_TO_ID[OPPOSITE[ID_TO_REL[gt_id]]]
            margin[global_index] = (
                scores[local_index, :, gt_id]
                - scores[local_index, :, opposite_id]
            )

    return pred, margin


def post_wo_norms_batched(x: np.ndarray, grams: np.ndarray) -> np.ndarray:
    x = np.asarray(x, dtype=np.float64)
    grams = np.asarray(grams, dtype=np.float64)
    xg = np.einsum("nhd,hde->nhe", x, grams, optimize=True)
    return np.sqrt(
        np.clip(
            np.einsum("nhe,nhe->nh", xg, x, optimize=True),
            0.0,
            None,
        )
    )

def post_wo_norms(x: np.ndarray, gram: np.ndarray) -> np.ndarray:
    x = np.asarray(x, dtype=np.float64)
    gram = np.asarray(gram, dtype=np.float64)
    xg = x @ gram
    return np.sqrt(np.clip(np.sum(xg * x, axis=1), 0.0, None))


# -----------------------------------------------------------------------------
# Scan phase
# -----------------------------------------------------------------------------


def collect_scan_arrays(
    *,
    source_dir: Path,
    rows: Sequence[Mapping[str, Any]],
    selected_layers: Sequence[int],
) -> Dict[str, Any]:
    if not rows:
        raise RuntimeError("No scan rows")

    first = load_cache(cache_path(source_dir, int(rows[0]["sid"])))
    source_layers = list(map(int, first["layers"].tolist()))
    source_lookup = {layer: index for index, layer in enumerate(source_layers)}
    missing = sorted(set(selected_layers) - set(source_lookup))
    if missing:
        raise RuntimeError(f"Layers missing from source caches: {missing}")

    layer_indices = [source_lookup[int(layer)] for layer in selected_layers]
    labels: List[int] = []
    folds: List[int] = []
    statuses: List[str] = []
    sids: List[int] = []
    head_visual: List[np.ndarray] = []
    qk_pred: List[np.ndarray] = []
    qk_margin: List[np.ndarray] = []
    visual_mass: List[np.ndarray] = []
    object_pair: List[np.ndarray] = []

    for row in tqdm(rows, desc="load-v3-producer-cache"):
        cache = load_cache(cache_path(source_dir, int(row["sid"])))
        labels.append(int(row["label"]))
        folds.append(int(row["fold"]))
        statuses.append(str(row["generation_pair_status"]))
        sids.append(int(row["sid"]))
        head_visual.append(
            np.asarray(cache["head_visual_pair_pre"])[layer_indices]
        )
        qk_pred.append(
            np.asarray(cache["attention_centroid_pred"])[layer_indices]
        )
        qk_margin.append(
            np.asarray(cache["attention_centroid_gt_margin"])[layer_indices]
        )
        visual_mass.append(
            np.asarray(cache["visual_attention_mass"])[layer_indices]
        )
        object_pair.append(
            np.asarray(cache["object_pair"])[layer_indices]
        )

    return {
        "layers": np.asarray(selected_layers, dtype=np.int64),
        "sids": np.asarray(sids, dtype=np.int64),
        "labels": np.asarray(labels, dtype=np.int64),
        "folds": np.asarray(folds, dtype=np.int64),
        "statuses": np.asarray(statuses, dtype=object),
        "head_visual_pair_pre": np.stack(head_visual, axis=0).astype(np.float32),
        "qk_pred": np.stack(qk_pred, axis=0).astype(np.int64),
        "qk_margin": np.stack(qk_margin, axis=0).astype(np.float32),
        "visual_mass": np.stack(visual_mass, axis=0).astype(np.float32),
        "object_pair": np.stack(object_pair, axis=0).astype(np.float32),
    }


def scan_producer_heads(
    *,
    args: argparse.Namespace,
    v3: Any,
    attention_helper: Any,
    decoder_layers: Sequence[Any],
    scan: Mapping[str, Any],
    output_dir: Path,
) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
    labels = np.asarray(scan["labels"], dtype=np.int64)
    folds = np.asarray(scan["folds"], dtype=np.int64)
    layers = np.asarray(scan["layers"], dtype=np.int64)
    head_visual = np.asarray(scan["head_visual_pair_pre"], dtype=np.float32)
    qk_pred = np.asarray(scan["qk_pred"], dtype=np.int64)
    qk_margin = np.asarray(scan["qk_margin"], dtype=np.float32)
    visual_mass = np.asarray(scan["visual_mass"], dtype=np.float32)
    object_pair = np.asarray(scan["object_pair"], dtype=np.float32)

    n_samples, n_selected_layers, n_heads, head_dim = head_visual.shape
    print(
        f"Producer scan: N={n_samples}, layers={layers.tolist()}, "
        f"heads={n_heads}, head_dim={head_dim}",
        flush=True,
    )

    object_pair_margins: Dict[int, np.ndarray] = {}
    for local_layer, layer in enumerate(layers.tolist()):
        _, margin, _ = v3.crossfit_centroids(
            object_pair[:, local_layer, :],
            labels,
            folds,
            args.centroid_metric,
        )
        object_pair_margins[int(layer)] = margin

    metrics: List[Dict[str, Any]] = []
    per_sample_store: Dict[Tuple[int, int], Dict[str, np.ndarray]] = {}

    for local_layer, layer in enumerate(layers.tolist()):
        attention = attention_helper.resolve_self_attention(
            decoder_layers[int(layer)]
        )
        o_weight_t = attention_helper.reshape_o_projection(
            attention,
            n_heads=n_heads,
            head_dim=head_dim,
        ).detach().float()  # [D,H,Dh], remains on model device
        grams = torch.einsum(
            "ohd,ohe->hde",
            o_weight_t,
            o_weight_t,
        ).detach().double().cpu().numpy()
        del o_weight_t

        x_layer = head_visual[:, local_layer, :, :].astype(np.float64)
        identity_grams = np.broadcast_to(
            np.eye(head_dim, dtype=np.float64)[None, :, :],
            (n_heads, head_dim, head_dim),
        )
        pre_pred_all, pre_margin_all = crossfit_metric_centroids_batched(
            x_layer,
            labels,
            folds,
            identity_grams,
            args.centroid_metric,
        )
        post_pred_all, post_margin_all = crossfit_metric_centroids_batched(
            x_layer,
            labels,
            folds,
            grams,
            args.centroid_metric,
        )
        norms_all = post_wo_norms_batched(x_layer, grams)

        for head in range(n_heads):
            pre_pred = pre_pred_all[:, head]
            pre_margin = pre_margin_all[:, head]
            post_pred = post_pred_all[:, head]
            post_margin = post_margin_all[:, head]
            norms = norms_all[:, head]

            qk_accuracy = float(
                np.mean(qk_pred[:, local_layer, head] == labels)
            )
            pre_accuracy = float(np.mean(pre_pred == labels))
            post_accuracy = float(np.mean(post_pred == labels))
            joint_min = float(min(qk_accuracy, post_accuracy))
            joint_geomean = float(
                math.sqrt(max(qk_accuracy, 0.0) * max(post_accuracy, 0.0))
            )

            metrics.append(
                {
                    "layer": int(layer),
                    "head": int(head),
                    "N": int(n_samples),
                    "qk_attention_centroid_accuracy": qk_accuracy,
                    "qk_attention_centroid_macro_accuracy": macro_accuracy(
                        qk_pred[:, local_layer, head],
                        labels,
                    ),
                    "qk_gt_margin_mean": safe_mean(
                        qk_margin[:, local_layer, head]
                    ),
                    "qk_gt_margin_positive_rate": safe_mean(
                        qk_margin[:, local_layer, head] > 0
                    ),
                    "visual_attention_mass_mean": safe_mean(
                        visual_mass[:, local_layer, head]
                    ),
                    "pre_ov_centroid_accuracy": pre_accuracy,
                    "pre_ov_centroid_macro_accuracy": macro_accuracy(
                        pre_pred,
                        labels,
                    ),
                    "pre_ov_gt_margin_mean": safe_mean(pre_margin),
                    "post_ov_centroid_accuracy": post_accuracy,
                    "post_ov_centroid_macro_accuracy": macro_accuracy(
                        post_pred,
                        labels,
                    ),
                    "post_ov_gt_margin_mean": safe_mean(post_margin),
                    "post_ov_write_norm_mean": safe_mean(norms),
                    "post_ov_write_norm_median": safe_median(norms),
                    "wo_accuracy_delta": float(post_accuracy - pre_accuracy),
                    "pre_vs_object_margin_corr": safe_corr(
                        pre_margin,
                        object_pair_margins[int(layer)],
                    ),
                    "post_vs_object_margin_corr": safe_corr(
                        post_margin,
                        object_pair_margins[int(layer)],
                    ),
                    "qk_vs_post_margin_corr": safe_corr(
                        qk_margin[:, local_layer, head],
                        post_margin,
                    ),
                    "joint_min": joint_min,
                    "joint_geomean": joint_geomean,
                }
            )
            per_sample_store[(int(layer), int(head))] = {
                "pre_margin": np.asarray(pre_margin, dtype=np.float32),
                "post_margin": np.asarray(post_margin, dtype=np.float32),
                "post_norm": np.asarray(norms, dtype=np.float32),
                "qk_margin": np.asarray(
                    qk_margin[:, local_layer, head],
                    dtype=np.float32,
                ),
            }

    write_csv(output_dir / "producer_head_metrics.csv", metrics)

    eligible = [
        row for row in metrics
        if float(row["visual_attention_mass_mean"]) >= args.min_visual_mass
    ]
    ranked = sorted(
        eligible,
        key=lambda row: (
            float(row[args.rank_metric]),
            float(row["post_ov_centroid_accuracy"]),
            float(row["qk_attention_centroid_accuracy"]),
        ),
        reverse=True,
    )
    top = ranked[: args.top_heads]
    top_rows: List[Dict[str, Any]] = []
    for rank, row in enumerate(top, start=1):
        item = dict(row)
        item["rank"] = rank
        top_rows.append(item)
    write_json(output_dir / "producer_top_heads.json", top_rows)

    if args.save_top_per_sample:
        per_sample_path = output_dir / "producer_top_per_sample.jsonl"
        per_sample_path.unlink(missing_ok=True)
        sids = np.asarray(scan["sids"], dtype=np.int64)
        for item in top_rows:
            layer = int(item["layer"])
            head = int(item["head"])
            values = per_sample_store[(layer, head)]
            for index, sid in enumerate(sids.tolist()):
                append_jsonl(
                    per_sample_path,
                    {
                        "rank": int(item["rank"]),
                        "layer": layer,
                        "head": head,
                        "sid": int(sid),
                        "gt": ID_TO_REL[int(labels[index])],
                        "fold": int(folds[index]),
                        "qk_margin": float(values["qk_margin"][index]),
                        "pre_ov_margin": float(values["pre_margin"][index]),
                        "post_ov_margin": float(values["post_margin"][index]),
                        "post_ov_write_norm": float(values["post_norm"][index]),
                    },
                )

    return metrics, top_rows


# -----------------------------------------------------------------------------
# Causal producer interventions
# -----------------------------------------------------------------------------


class AttentionTargetDelta:
    """Add residual-space deltas to selected token rows of attention output."""

    def __init__(
        self,
        attention_module: torch.nn.Module,
        position_to_delta: Mapping[int, np.ndarray],
    ):
        self.position_to_delta = {
            int(position): np.asarray(delta, dtype=np.float32)
            for position, delta in position_to_delta.items()
        }
        self.applied = False
        self.handle = attention_module.register_forward_hook(self._hook)

    def _hook(self, module: Any, inputs: Tuple[Any, ...], output: Any) -> Any:
        hidden = first_tensor(output)
        modified = hidden.clone()
        applied = 0
        for position, delta_np in self.position_to_delta.items():
            if not 0 <= position < int(hidden.shape[1]):
                raise RuntimeError(
                    f"Intervention position {position} outside sequence length "
                    f"{int(hidden.shape[1])}"
                )
            delta = torch.as_tensor(
                delta_np,
                device=hidden.device,
                dtype=hidden.dtype,
            )
            modified[:, position, :] = modified[:, position, :] + delta
            applied += 1
        self.applied = applied > 0
        return replace_first_tensor(output, modified)

    def close(self) -> None:
        with contextlib.suppress(Exception):
            self.handle.remove()

    def __enter__(self) -> "AttentionTargetDelta":
        return self

    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None:
        self.close()


def first_tensor(output: Any) -> torch.Tensor:
    if torch.is_tensor(output):
        return output
    if isinstance(output, (tuple, list)):
        for value in output:
            if torch.is_tensor(value) and value.ndim == 3:
                return value
    for name in ("last_hidden_state", "hidden_states"):
        value = getattr(output, name, None)
        if torch.is_tensor(value) and value.ndim == 3:
            return value
    raise TypeError(f"Cannot locate 3D tensor in {type(output).__name__}")


def replace_first_tensor(output: Any, modified: torch.Tensor) -> Any:
    if torch.is_tensor(output):
        return modified
    if isinstance(output, tuple):
        values = list(output)
        for index, value in enumerate(values):
            if torch.is_tensor(value) and value.ndim == 3:
                values[index] = modified
                return tuple(values)
    if isinstance(output, list):
        values = list(output)
        for index, value in enumerate(values):
            if torch.is_tensor(value) and value.ndim == 3:
                values[index] = modified
                return values
    raise TypeError(f"Cannot replace 3D tensor in {type(output).__name__}")


def target_local_index(trace: Any, position: int) -> int:
    lookup = {
        int(global_position): local
        for local, global_position in enumerate(trace.target_positions)
    }
    if int(position) not in lookup:
        raise KeyError(
            f"Target position {position} absent from trace targets "
            f"{trace.target_positions}"
        )
    return int(lookup[int(position)])


def visual_pre_vector(
    *,
    trace: Any,
    head: int,
    target_position: int,
    visual_positions: Sequence[int],
    routing_trace: Optional[Any] = None,
    routing_target_position: Optional[int] = None,
    value_trace: Optional[Any] = None,
) -> torch.Tensor:
    routing = routing_trace if routing_trace is not None else trace
    values_source = value_trace if value_trace is not None else trace
    routing_target = (
        int(routing_target_position)
        if routing_target_position is not None
        else int(target_position)
    )
    local = target_local_index(routing, routing_target)
    visual = torch.as_tensor(
        list(map(int, visual_positions)),
        dtype=torch.long,
    )
    weights = routing.attention_weights[int(head), local].index_select(
        0,
        visual,
    ).float()
    values = values_source.value_states[int(head)].index_select(
        0,
        visual,
    ).float()
    return torch.einsum("s,sd->d", weights, values)


def project_one_head(
    trace: Any,
    head: int,
    pre_vector: torch.Tensor,
) -> torch.Tensor:
    weight = trace.o_proj_weight[:, int(head), :].float()
    return torch.einsum("d,od->o", pre_vector.float(), weight)


def aligned_position_pairs(
    original_positions: Sequence[int],
    swapped_positions: Sequence[int],
) -> List[Tuple[int, int]]:
    original = list(map(int, original_positions))
    swapped = list(map(int, swapped_positions))
    if len(original) != len(swapped):
        raise RuntimeError(
            f"Identity-aligned object token lengths differ: "
            f"{len(original)} vs {len(swapped)}"
        )
    return list(zip(original, swapped))


def build_condition_deltas(
    *,
    condition: str,
    heads: Sequence[int],
    original_trace: Any,
    swapped_trace: Any,
    original_a_positions: Sequence[int],
    original_b_positions: Sequence[int],
    swapped_a_positions: Sequence[int],
    swapped_b_positions: Sequence[int],
    visual_positions_original: Sequence[int],
    visual_positions_swapped: Sequence[int],
) -> Tuple[str, Dict[int, np.ndarray]]:
    if list(map(int, visual_positions_original)) != list(map(int, visual_positions_swapped)):
        raise RuntimeError(
            "Original/swapped visual token positions differ; QK routing replacement "
            "requires aligned visual source positions."
        )

    identity_pairs = (
        aligned_position_pairs(original_a_positions, swapped_a_positions)
        + aligned_position_pairs(original_b_positions, swapped_b_positions)
    )

    target_side = (
        "original"
        if condition in {
            "qk_swap_on_original",
            "ov_visual_ablate_on_original",
        }
        else "swapped"
    )
    deltas: Dict[int, torch.Tensor] = {}

    for original_position, swapped_position in identity_pairs:
        target_position = (
            original_position if target_side == "original" else swapped_position
        )
        total = None

        for head in heads:
            original_full = visual_pre_vector(
                trace=original_trace,
                head=head,
                target_position=original_position,
                visual_positions=visual_positions_original,
            )
            swapped_full = visual_pre_vector(
                trace=swapped_trace,
                head=head,
                target_position=swapped_position,
                visual_positions=visual_positions_swapped,
            )

            if condition == "qk_swap_on_original":
                routed = visual_pre_vector(
                    trace=original_trace,
                    head=head,
                    target_position=original_position,
                    visual_positions=visual_positions_original,
                    routing_trace=swapped_trace,
                    routing_target_position=swapped_position,
                    value_trace=original_trace,
                )
                delta_head = project_one_head(
                    original_trace,
                    head,
                    routed - original_full,
                )

            elif condition == "ov_visual_ablate_on_original":
                delta_head = -project_one_head(
                    original_trace,
                    head,
                    original_full,
                )

            elif condition == "qk_restore_on_swapped":
                routed = visual_pre_vector(
                    trace=swapped_trace,
                    head=head,
                    target_position=swapped_position,
                    visual_positions=visual_positions_swapped,
                    routing_trace=original_trace,
                    routing_target_position=original_position,
                    value_trace=swapped_trace,
                )
                delta_head = project_one_head(
                    swapped_trace,
                    head,
                    routed - swapped_full,
                )

            elif condition == "full_visual_write_restore_on_swapped":
                original_write = project_one_head(
                    original_trace,
                    head,
                    original_full,
                )
                swapped_write = project_one_head(
                    swapped_trace,
                    head,
                    swapped_full,
                )
                delta_head = original_write - swapped_write

            else:
                raise ValueError(condition)

            total = delta_head if total is None else total + delta_head

        if total is None:
            raise RuntimeError("No heads supplied to intervention")
        if target_position in deltas:
            deltas[target_position] = deltas[target_position] + total
        else:
            deltas[target_position] = total

    return target_side, {
        int(position): tensor.detach().float().cpu().numpy()
        for position, tensor in deltas.items()
    }


@torch.inference_mode()
def run_margin(
    *,
    model: Any,
    base: Any,
    relation_token_map: Mapping[str, Sequence[int]],
    batch: Mapping[str, Any],
    gt_original_axis: str,
    attention_module: Optional[torch.nn.Module] = None,
    deltas: Optional[Mapping[int, np.ndarray]] = None,
) -> Dict[str, Any]:
    intervention: Optional[AttentionTargetDelta] = None
    try:
        if attention_module is not None:
            if not deltas:
                raise ValueError("attention_module provided without deltas")
            intervention = AttentionTargetDelta(
                attention_module,
                deltas,
            )
        outputs = model(
            **batch,
            use_cache=False,
            return_dict=True,
        )
        if intervention is not None and not intervention.applied:
            raise RuntimeError("Attention intervention hook did not fire")
        relation = base.relation_scores(
            outputs.logits[0, -1],
            dict(relation_token_map),
            gt=None,
        )
        logits = np.asarray(relation["logits"], dtype=np.float64)
        return {
            "logits": logits.tolist(),
            "prediction": str(relation["prediction"]),
            "margin": relation_margin(logits, gt_original_axis),
        }
    finally:
        if intervention is not None:
            intervention.close()
        with contextlib.suppress(Exception):
            del outputs


def parse_causal_heads(
    value: str,
    top_path: Path,
) -> List[Tuple[int, int]]:
    text = str(value).strip().lower()
    if text == "top":
        if not top_path.exists():
            raise FileNotFoundError(top_path)
        values = json.loads(top_path.read_text(encoding="utf-8"))
        return [
            (int(item["layer"]), int(item["head"]))
            for item in values
        ]

    result = []
    for item in str(value).split(","):
        item = item.strip()
        if not item:
            continue
        layer_text, head_text = item.split(":", 1)
        result.append((int(layer_text), int(head_text)))
    if not result:
        raise ValueError("No causal heads selected")
    return list(dict.fromkeys(result))


def causal_units(
    selected_heads: Sequence[Tuple[int, int]],
    include_unions: bool,
) -> List[Dict[str, Any]]:
    units: List[Dict[str, Any]] = []
    for rank, (layer, head) in enumerate(selected_heads, start=1):
        units.append(
            {
                "unit": f"top_rank_{rank}",
                "layer": int(layer),
                "heads": [int(head)],
            }
        )

    if include_unions:
        grouped: Dict[int, List[int]] = defaultdict(list)
        for layer, head in selected_heads:
            grouped[int(layer)].append(int(head))
        for layer, heads in sorted(grouped.items()):
            unique = sorted(set(heads))
            if len(unique) > 1:
                units.append(
                    {
                        "unit": f"top_union_L{layer}",
                        "layer": int(layer),
                        "heads": unique,
                    }
                )
    return units


def run_causal_phase(
    *,
    args: argparse.Namespace,
    v3: Any,
    base: Any,
    attention_helper: Any,
    model: Any,
    processor: Any,
    decoder_layers: Sequence[Any],
    relation_token_map: Mapping[str, Sequence[int]],
    source_rows: Sequence[Mapping[str, Any]],
    records_by_sid: Mapping[int, Any],
    prompt_rows: Mapping[int, Mapping[str, Any]],
    output_dir: Path,
) -> List[Dict[str, Any]]:
    selected_heads = parse_causal_heads(
        args.causal_heads,
        output_dir / "producer_top_heads.json",
    )
    units = causal_units(
        selected_heads,
        args.causal_layer_unions,
    )
    selected_layers = sorted({int(unit["layer"]) for unit in units})
    conditions = parse_conditions(args.causal_conditions)

    eligible = [
        dict(row) for row in source_rows
        if status_matches(row, args.causal_status)
    ]
    filtered: List[Dict[str, Any]] = []
    for row in eligible:
        original_cached_margin = float(row["baseline_lm_margin"])
        swapped_cached_margin = relation_margin(
            row["swapped_relation_logits"],
            str(row["gt"]),
        )
        if abs(original_cached_margin - swapped_cached_margin) < args.min_margin_denominator:
            continue
        if args.causal_require_margin_sign and not (
            original_cached_margin > 0 and swapped_cached_margin < 0
        ):
            continue
        filtered.append(row)
    eligible = filtered
    eligible = stratified_limit(
        eligible,
        args.causal_max_samples,
        args.seed,
    )
    if not eligible:
        raise RuntimeError("No samples eligible for producer causal validation")

    print(
        f"Producer causal: N={len(eligible)}, layers={selected_layers}, "
        f"units={len(units)}, conditions={conditions}",
        flush=True,
    )

    output_path = output_dir / "producer_causal.jsonl"
    errors_path = output_dir / "errors.jsonl"
    existing = read_jsonl(output_path) if args.resume else []
    completed = {
        (
            int(row["sid"]),
            str(row["unit"]),
            str(row["condition"]),
        )
        for row in existing
    }

    rows = list(existing)
    device = torch.device(args.device)
    processed_samples = 0

    for row in tqdm(eligible, desc=f"producer-causal:{args.model}"):
        sid = int(row["sid"])
        image: Optional[Image.Image] = None
        original_batch: Optional[Dict[str, Any]] = None
        swapped_batch: Optional[Dict[str, Any]] = None

        try:
            prompt = prompt_rows[sid]
            subject = str(prompt["subject"])
            reference = str(prompt["reference"])
            original_question = str(prompt["question_text"])
            swapped_question = base.build_swapped_question(subject, reference)
            gt = str(row["gt"])
            swapped_gt = OPPOSITE[gt]

            image = base.record_image(records_by_sid[sid])
            original_batch = base.make_question_batch(
                processor=processor,
                image=image,
                question_text=original_question,
                device=device,
            )
            swapped_batch = base.make_question_batch(
                processor=processor,
                image=image,
                question_text=swapped_question,
                device=device,
            )

            original_ids = original_batch["input_ids"][0].detach().cpu().tolist()
            swapped_ids = swapped_batch["input_ids"][0].detach().cpu().tolist()

            original_a_span, original_b_span = base.locate_object_spans(
                processor.tokenizer,
                original_ids,
                subject,
                reference,
            )
            swapped_b_span, swapped_a_span = base.locate_object_spans(
                processor.tokenizer,
                swapped_ids,
                reference,
                subject,
            )

            original_a_positions = v3.span_positions(
                original_a_span,
                args.object_state,
            )
            original_b_positions = v3.span_positions(
                original_b_span,
                args.object_state,
            )
            swapped_a_positions = v3.span_positions(
                swapped_a_span,
                args.object_state,
            )
            swapped_b_positions = v3.span_positions(
                swapped_b_span,
                args.object_state,
            )

            original_targets = sorted(
                set(original_a_positions + original_b_positions)
            )
            swapped_targets = sorted(
                set(swapped_a_positions + swapped_b_positions)
            )

            original_visual = base.resolve_visual_indices(
                model,
                processor,
                dict(original_batch),
                original_ids,
            )
            swapped_visual = base.resolve_visual_indices(
                model,
                processor,
                dict(swapped_batch),
                swapped_ids,
            )

            original_baseline, original_traces = v3.trace_prompt_chunks(
                attention_helper=attention_helper,
                model=model,
                batch=original_batch,
                relation_token_map=relation_token_map,
                decoder_layers=decoder_layers,
                layers=selected_layers,
                target_positions=original_targets,
                chunk_size=args.trace_layer_chunk,
            )
            swapped_baseline, swapped_traces = v3.trace_prompt_chunks(
                attention_helper=attention_helper,
                model=model,
                batch=swapped_batch,
                relation_token_map=relation_token_map,
                decoder_layers=decoder_layers,
                layers=selected_layers,
                target_positions=swapped_targets,
                chunk_size=args.trace_layer_chunk,
            )

            original_margin = relation_margin(
                [original_baseline["scores"][relation] for relation in RELATIONS],
                gt,
            )
            swapped_margin = relation_margin(
                [swapped_baseline["scores"][relation] for relation in RELATIONS],
                gt,
            )
            denominator = float(original_margin - swapped_margin)
            if abs(denominator) < args.min_margin_denominator:
                continue
            if args.causal_require_margin_sign and not (
                original_margin > 0 and swapped_margin < 0
            ):
                continue

            max_replay_error = max(
                [
                    float(original_traces[layer].replay_relative_error)
                    for layer in selected_layers
                ]
                + [
                    float(swapped_traces[layer].replay_relative_error)
                    for layer in selected_layers
                ]
            )

            for unit in units:
                layer = int(unit["layer"])
                heads = list(map(int, unit["heads"]))
                attention_module = attention_helper.resolve_self_attention(
                    decoder_layers[layer]
                )

                for condition in conditions:
                    key = (sid, str(unit["unit"]), condition)
                    if key in completed:
                        continue
                    try:
                        target_side, deltas = build_condition_deltas(
                            condition=condition,
                            heads=heads,
                            original_trace=original_traces[layer],
                            swapped_trace=swapped_traces[layer],
                            original_a_positions=original_a_positions,
                            original_b_positions=original_b_positions,
                            swapped_a_positions=swapped_a_positions,
                            swapped_b_positions=swapped_b_positions,
                            visual_positions_original=original_visual,
                            visual_positions_swapped=swapped_visual,
                        )
                        target_batch = (
                            original_batch
                            if target_side == "original"
                            else swapped_batch
                        )
                        intervention = run_margin(
                            model=model,
                            base=base,
                            relation_token_map=relation_token_map,
                            batch=target_batch,
                            gt_original_axis=gt,
                            attention_module=attention_module,
                            deltas=deltas,
                        )
                        intervened_margin = float(intervention["margin"])

                        if target_side == "original":
                            raw_effect = float(original_margin - intervened_margin)
                            normalized_effect = float(raw_effect / denominator)
                            expected_positive = raw_effect > 0
                            crossed = intervened_margin < 0
                            metric_name = "normalized_damage"
                        else:
                            raw_effect = float(intervened_margin - swapped_margin)
                            normalized_effect = float(raw_effect / denominator)
                            expected_positive = raw_effect > 0
                            crossed = intervened_margin > 0
                            metric_name = "normalized_recovery"

                        result = {
                            "script_version": SCRIPT_VERSION,
                            "model": args.model,
                            "sid": sid,
                            "gt": gt,
                            "swapped_gt": swapped_gt,
                            "generation_pair_status": row["generation_pair_status"],
                            "unit": str(unit["unit"]),
                            "layer": layer,
                            "heads": heads,
                            "condition": condition,
                            "target_side": target_side,
                            "original_margin": float(original_margin),
                            "swapped_margin_fixed_axis": float(swapped_margin),
                            "intervened_margin_fixed_axis": intervened_margin,
                            "margin_denominator": denominator,
                            "raw_effect": raw_effect,
                            "normalized_effect": normalized_effect,
                            "normalized_metric": metric_name,
                            "expected_positive": bool(expected_positive),
                            "crossed_decision_boundary": bool(crossed),
                            "intervened_prediction": intervention["prediction"],
                            "max_replay_relative_error": max_replay_error,
                            "replay_within_tolerance": bool(
                                max_replay_error <= args.replay_tolerance
                            ),
                        }
                        append_jsonl(output_path, result)
                        rows.append(result)
                        completed.add(key)
                    except Exception as exc:
                        append_jsonl(
                            errors_path,
                            {
                                "phase": "causal",
                                "sid": sid,
                                "unit": unit["unit"],
                                "layer": layer,
                                "heads": heads,
                                "condition": condition,
                                "error_type": type(exc).__name__,
                                "error": str(exc),
                                "traceback": traceback.format_exc(),
                            },
                        )
                        print(
                            f"\n[ERROR causal sid={sid} {unit['unit']} "
                            f"{condition}] {type(exc).__name__}: {exc}",
                            flush=True,
                        )
                        if args.fail_fast:
                            raise

            processed_samples += 1
            if args.print_every > 0 and processed_samples % args.print_every == 0:
                print(
                    f"[causal {processed_samples}/{len(eligible)}] sid={sid} "
                    f"gt={gt} M_orig={original_margin:+.5f} "
                    f"M_swap={swapped_margin:+.5f} "
                    f"replay={max_replay_error:.3e}",
                    flush=True,
                )

        except Exception as exc:
            append_jsonl(
                errors_path,
                {
                    "phase": "sample_setup",
                    "sid": sid,
                    "error_type": type(exc).__name__,
                    "error": str(exc),
                    "traceback": traceback.format_exc(),
                },
            )
            print(
                f"\n[ERROR sample sid={sid}] {type(exc).__name__}: {exc}",
                flush=True,
            )
            if args.fail_fast:
                raise
        finally:
            if image is not None:
                with contextlib.suppress(Exception):
                    image.close()
            if original_batch is not None:
                del original_batch
            if swapped_batch is not None:
                del swapped_batch
            gc.collect()
            if torch.cuda.is_available() and (
                args.empty_cache_every <= 1
                or max(processed_samples, 1) % args.empty_cache_every == 0
            ):
                torch.cuda.empty_cache()

    rows.sort(
        key=lambda item: (
            str(item["unit"]),
            str(item["condition"]),
            int(item["sid"]),
        )
    )
    output_path.unlink(missing_ok=True)
    for result in rows:
        append_jsonl(output_path, result)

    summary = summarize_causal(rows)
    write_csv(output_dir / "producer_causal_summary.csv", summary)
    return rows


def summarize_causal(rows: Sequence[Mapping[str, Any]]) -> List[Dict[str, Any]]:
    groups: Dict[Tuple[str, int, str], List[Mapping[str, Any]]] = defaultdict(list)
    for row in rows:
        groups[
            (
                str(row["unit"]),
                int(row["layer"]),
                str(row["condition"]),
            )
        ].append(row)

    summary: List[Dict[str, Any]] = []
    for (unit, layer, condition), values in sorted(groups.items()):
        summary.append(
            {
                "unit": unit,
                "layer": layer,
                "condition": condition,
                "heads": json.dumps(values[0]["heads"]),
                "N": len(values),
                "mean_raw_effect": safe_mean(
                    row["raw_effect"] for row in values
                ),
                "median_raw_effect": safe_median(
                    row["raw_effect"] for row in values
                ),
                "mean_normalized_effect": safe_mean(
                    row["normalized_effect"] for row in values
                ),
                "median_normalized_effect": safe_median(
                    row["normalized_effect"] for row in values
                ),
                "positive_effect_rate": safe_mean(
                    int(bool(row["expected_positive"])) for row in values
                ),
                "crossed_decision_boundary_rate": safe_mean(
                    int(bool(row["crossed_decision_boundary"])) for row in values
                ),
                "replay_within_tolerance_rate": safe_mean(
                    int(bool(row["replay_within_tolerance"])) for row in values
                ),
            }
        )
    return summary


# -----------------------------------------------------------------------------
# Report
# -----------------------------------------------------------------------------


def write_report(
    *,
    output_dir: Path,
    args: argparse.Namespace,
    scan_rows: Sequence[Mapping[str, Any]],
    top_rows: Sequence[Mapping[str, Any]],
    causal_summary: Sequence[Mapping[str, Any]],
) -> None:
    lines = [
        f"script_version: {SCRIPT_VERSION}",
        f"model: {args.model}",
        f"source_output_dir: {args.source_output_dir}",
        "",
    ]

    if scan_rows:
        lines.extend(
            [
                "TOP PRODUCER HEADS",
                (
                    "QK=functional object->visual routing; "
                    "preOV=A·V head-local relation read; "
                    "postOV=W_O(A·V) residual relation write."
                ),
            ]
        )
        for item in top_rows:
            lines.append(
                f"rank={int(item['rank'])} "
                f"L{int(item['layer'])} H{int(item['head'])} "
                f"QK={float(item['qk_attention_centroid_accuracy']):.4f} "
                f"preOV={float(item['pre_ov_centroid_accuracy']):.4f} "
                f"postOV={float(item['post_ov_centroid_accuracy']):.4f} "
                f"mass={float(item['visual_attention_mass_mean']):.6f} "
                f"writeNorm={float(item['post_ov_write_norm_mean']):.6f} "
                f"joint={float(item[args.rank_metric]):.4f}"
            )
        lines.append("")

    if causal_summary:
        lines.append("PRODUCER CAUSAL VALIDATION")
        ranked = sorted(
            causal_summary,
            key=lambda row: float(row["mean_normalized_effect"]),
            reverse=True,
        )
        for row in ranked[:40]:
            lines.append(
                f"{row['unit']} L{int(row['layer'])} "
                f"{row['condition']} N={int(row['N'])} "
                f"effect={float(row['mean_normalized_effect']):+.6f} "
                f"raw={float(row['mean_raw_effect']):+.6f} "
                f"positive={float(row['positive_effect_rate']):.4f} "
                f"crossed={float(row['crossed_decision_boundary_rate']):.4f} "
                f"replayOK={float(row['replay_within_tolerance_rate']):.4f}"
            )
        lines.extend(
            [
                "",
                "Interpretation:",
                "  qk_swap_on_original / qk_restore_on_swapped isolate the",
                "  selected head's object->visual routing pattern while holding",
                "  the target run's visual V states fixed.",
                "  ov_visual_ablate_on_original removes the selected head's",
                "  actual post-W_O visual write at object tokens.",
                "  full_visual_write_restore_on_swapped restores the complete",
                "  A·V·W_O producer contribution and is a sufficiency test.",
                "  These results identify producer heads. They do not yet identify",
                "  the downstream receiver Q/K/V composition path.",
            ]
        )

    (output_dir / "report.txt").write_text(
        "\n".join(lines) + "\n",
        encoding="utf-8",
    )


# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------


def main() -> None:
    args = parse_args()
    if args.device.startswith("cuda") and not torch.cuda.is_available():
        raise RuntimeError("CUDA requested but unavailable")
    if args.top_heads < 1:
        raise ValueError("--top-heads must be >= 1")
    if args.trace_layer_chunk < 1:
        raise ValueError("--trace-layer-chunk must be >= 1")

    random.seed(args.seed)
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)

    output_dir = Path(args.output_dir)
    if args.overwrite and output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    source_dir = Path(args.source_output_dir)
    source_config_path = source_dir / "config.json"
    source_extraction_path = source_dir / "extraction.jsonl"
    if not source_config_path.exists():
        raise FileNotFoundError(source_config_path)
    if not source_extraction_path.exists():
        raise FileNotFoundError(source_extraction_path)

    source_config = json.loads(
        source_config_path.read_text(encoding="utf-8")
    )
    source_rows = read_jsonl(source_extraction_path)
    if args.max_samples is not None:
        source_rows = source_rows[: int(args.max_samples)]
    if not source_rows:
        raise RuntimeError("Source extraction is empty")

    if str(source_config.get("model")) != args.model:
        raise RuntimeError(
            f"Source model={source_config.get('model')} but --model={args.model}"
        )
    if str(source_config.get("dataset")) != args.dataset:
        raise RuntimeError(
            f"Source dataset={source_config.get('dataset')} "
            f"but --dataset={args.dataset}"
        )

    v3 = import_file(Path(args.v3_script), "producer_qk_ov_v3")
    base = import_file(Path(args.base_script), "producer_qk_ov_base")
    attention_helper = import_file(
        Path(args.attention_helper),
        "producer_qk_ov_attention",
    )

    model = None
    processor = None
    scan_rows: List[Dict[str, Any]] = []
    top_rows: List[Dict[str, Any]] = []
    causal_rows: List[Dict[str, Any]] = []

    try:
        (
            model,
            processor,
            spec,
            decoder_layers,
            decoder_path,
            relation_token_map,
        ) = load_model_bundle(args=args, base=base)

        selected_layers = parse_layers(
            args.layers,
            source_config.get("selected_layers", []),
            len(decoder_layers),
        )

        config = {
            "script_version": SCRIPT_VERSION,
            "model": args.model,
            "repo_id": spec.repo_id,
            "dataset": args.dataset,
            "source_output_dir": str(source_dir),
            "source_script_version": source_config.get("script_version"),
            "selected_layers": selected_layers,
            "decoder_path": decoder_path,
            "object_state": args.object_state,
            "centroid_metric": args.centroid_metric,
            "scan_status": args.scan_status,
            "rank_metric": args.rank_metric,
            "top_heads": args.top_heads,
            "causal_status": args.causal_status,
            "causal_max_samples": args.causal_max_samples,
            "causal_conditions": parse_conditions(args.causal_conditions),
            "causal_require_margin_sign": args.causal_require_margin_sign,
            "transformers_version": transformers.__version__,
        }
        write_json(output_dir / "config.json", config)

        if args.phase in {"all", "scan"}:
            selected_scan_rows = [
                row for row in source_rows
                if status_matches(row, args.scan_status)
            ]
            scan = collect_scan_arrays(
                source_dir=source_dir,
                rows=selected_scan_rows,
                selected_layers=selected_layers,
            )
            scan_rows, top_rows = scan_producer_heads(
                args=args,
                v3=v3,
                attention_helper=attention_helper,
                decoder_layers=decoder_layers,
                scan=scan,
                output_dir=output_dir,
            )
        else:
            metrics_path = output_dir / "producer_head_metrics.csv"
            top_path = output_dir / "producer_top_heads.json"
            if not metrics_path.exists() or not top_path.exists():
                raise RuntimeError(
                    "--phase causal requires existing producer scan outputs"
                )
            with metrics_path.open("r", encoding="utf-8") as handle:
                scan_rows = list(csv.DictReader(handle))
            top_rows = json.loads(top_path.read_text(encoding="utf-8"))

        if args.phase in {"all", "causal"}:
            two_object = base.import_two_object_module()
            records, audit = two_object.load_records(
                args.dataset,
                Path(args.data_root),
                args.max_samples,
            )
            records_by_sid = {
                int(record.sid): record for record in records
            }
            prompt_rows = base.load_standard_prompts(
                Path(args.prompt_jsonl)
            )
            causal_rows = run_causal_phase(
                args=args,
                v3=v3,
                base=base,
                attention_helper=attention_helper,
                model=model,
                processor=processor,
                decoder_layers=decoder_layers,
                relation_token_map=relation_token_map,
                source_rows=source_rows,
                records_by_sid=records_by_sid,
                prompt_rows=prompt_rows,
                output_dir=output_dir,
            )

        causal_summary = (
            summarize_causal(causal_rows) if causal_rows else []
        )
        if causal_summary:
            write_csv(
                output_dir / "producer_causal_summary.csv",
                causal_summary,
            )

        write_report(
            output_dir=output_dir,
            args=args,
            scan_rows=scan_rows,
            top_rows=top_rows,
            causal_summary=causal_summary,
        )
        print(f"\nSaved outputs to {output_dir}", flush=True)

    finally:
        if model is not None:
            del model
        if processor is not None:
            del processor
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()


if __name__ == "__main__":
    main()
