#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Qwen2.5-VL-3B + COCO random-map analysis.

At every decoder layer, build TWO carrier-agnostic readouts:

    Spatial Readout(l)
      = max(
          relation readout from object-pair text state,
          relation readout from prompt-final state
        )

    Option Readout(l)
      = max(
          generated-option readout from object-pair text state,
          generated-option readout from prompt-final state
        )

The max is taken at the LAYER-LEVEL over held-out aggregate readout accuracy.
It is NOT a per-sample oracle.

Both readouts come from the same samples, the same randomized A/B/C/D question,
and the same Real-Gray forward states.

Spatial labels:
    left / right / above / below

Option labels:
    the A/B/C/D option ACTUALLY GENERATED by the model

No GT-option readout is plotted.

Outputs:
    spatial_option_readout_all.png
    spatial_option_readout_correct.png

Main plot styling is intentionally minimal:
    x-axis: Decoder Layer
    y-axis: Readout Accuracy
    legend: Spatial Readout / Option Readout
    no chance line
    no extra title

Run from the AdaptVis llava16 repository root.

Full run:
CUDA_VISIBLE_DEVICES=0 PYTHONUNBUFFERED=1 \
python -u qwen3b_coco_best_spatial_decision_readout_v2.py \
  --max-samples 0 \
  --eval-max-samples 0 \
  --output-dir output/qwen3b_coco_best_spatial_decision_readout_v2 \
  --overwrite

Quick run:
CUDA_VISIBLE_DEVICES=0 PYTHONUNBUFFERED=1 \
python -u qwen3b_coco_best_spatial_decision_readout_v2.py \
  --max-samples 160 \
  --eval-max-samples 80 \
  --output-dir output/qwen3b_coco_best_spatial_decision_readout_quick \
  --overwrite
"""

from __future__ import annotations

import argparse
import contextlib
import csv
import gc
import json
import random
import shutil
import traceback
from collections import Counter
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

import numpy as np
import torch
import transformers
from transformers import AutoProcessor
from tqdm import tqdm

# Existing random relation -> A/B/C/D protocol.
import eval_qwen_coco_randmap_late_spatial_deconfound_quick as rm

# Reuse the repository's already-debugged text-position -> decoder-position mapping.
import eval_multimodel_targetselected_head_spatial_control_genflip_trust_v6 as v6

base = rm.base
traj = rm.traj
REL = tuple(rm.REL)
LETTERS = tuple(rm.LETTERS)


def parse_args():
    p = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    p.add_argument("--data-root", default="data")
    p.add_argument(
        "--prompt-jsonl",
        default="prompts/COCO_QA_two_obj_with_answer_four_options.jsonl",
    )
    p.add_argument("--model", default="qwen-3b", choices=["qwen-3b"])
    p.add_argument(
        "--layers",
        default="all",
        help="all = every decoder block; otherwise comma list such as 20,21,22,23,24,25,26,27",
    )
    p.add_argument("--train-ratio", type=float, default=0.30)
    p.add_argument("--seed", type=int, default=17)
    p.add_argument(
        "--max-samples",
        type=int,
        default=0,
        help="0 = use all COCO-two samples before train/test split",
    )
    p.add_argument(
        "--eval-max-samples",
        type=int,
        default=0,
        help="0 = use all held-out TEST samples",
    )
    p.add_argument("--gray-value", type=int, default=128)
    p.add_argument("--max-new-tokens", type=int, default=4)
    p.add_argument("--device", default="cuda:0")
    p.add_argument(
        "--attn-impl",
        default="eager",
        choices=["eager", "sdpa", "flash_attention_2", "none"],
    )
    p.add_argument("--output-dir", required=True)
    p.add_argument("--overwrite", action="store_true")
    return p.parse_args()


def write_csv(path: Path, rows: List[dict]):
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return

    fields = []
    seen = set()
    for row in rows:
        for k in row:
            if k not in seen:
                fields.append(k)
                seen.add(k)

    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(rows)


def parse_layers(text: str, n_layers: int) -> List[int]:
    if text.strip().lower() == "all":
        return list(range(n_layers))

    out = sorted(
        {
            int(x.strip().upper().replace("L", ""))
            for x in text.split(",")
            if x.strip()
        }
    )
    bad = [x for x in out if not (0 <= x < n_layers)]
    if bad:
        raise ValueError(
            f"Invalid layers {bad}; model has L0-L{n_layers - 1}"
        )
    return out


def cosine_np(a: np.ndarray, b: np.ndarray) -> float:
    a = np.asarray(a, dtype=np.float64).reshape(-1)
    b = np.asarray(b, dtype=np.float64).reshape(-1)
    den = float(np.linalg.norm(a) * np.linalg.norm(b))
    if den <= 1e-12:
        return float("-inf")
    return float(np.dot(a, b) / den)


def nearest_centroid(
    x: np.ndarray,
    centroids: Dict[str, np.ndarray],
) -> str:
    labels = list(centroids)
    vals = [cosine_np(x, centroids[k]) for k in labels]
    vals = [-1e30 if not np.isfinite(v) else v for v in vals]
    return labels[int(np.argmax(vals))]


def make_gray_like(image, value: int):
    from PIL import Image

    v = int(max(0, min(255, value)))
    return Image.new("RGB", image.size, (v, v, v))


def capture_obj_and_last(
    *,
    model,
    processor,
    decoder_layers: Sequence,
    batch: Dict[str, torch.Tensor],
    subject: str,
    reference: str,
    layers: Sequence[int],
) -> Tuple[Dict[int, np.ndarray], Dict[int, np.ndarray]]:
    """
    One no-grad multimodal forward.

    Returns decoder-block output states:
        obj[L]  = mean(h_subject) - mean(h_reference)
        last[L] = h_prompt-final
    """
    ids = [
        int(x)
        for x in batch["input_ids"][0].detach().cpu().tolist()
    ]

    sub_raw = v6.hs.headprobe.locate_phrase_positions(
        processor.tokenizer,
        ids,
        subject,
    )
    ref_raw = v6.hs.headprobe.locate_phrase_positions(
        processor.tokenizer,
        ids,
        reference,
    )

    with torch.inference_mode():
        out = model(
            **batch,
            output_hidden_states=True,
            output_attentions=False,
            use_cache=False,
            return_dict=True,
        )

    hst = v6.extract_hidden_states(out)
    if len(hst) < len(decoder_layers) + 1:
        raise RuntimeError(
            f"hidden_states length={len(hst)} "
            f"but decoder layers={len(decoder_layers)}"
        )

    merged_len = int(hst[0].shape[1])

    sub_pos, _ = v6.recv.map_text_positions_to_decoder(
        model=model,
        processor=processor,
        input_ids=ids,
        raw_positions=sub_raw,
        merged_length=merged_len,
    )
    ref_pos, _ = v6.recv.map_text_positions_to_decoder(
        model=model,
        processor=processor,
        input_ids=ids,
        raw_positions=ref_raw,
        merged_length=merged_len,
    )

    if not sub_pos or not ref_pos:
        raise RuntimeError(
            "Could not map subject/reference positions "
            f"for subject={subject!r}, reference={reference!r}"
        )

    obj = {}
    last = {}

    for L in layers:
        h = hst[int(L) + 1][0]

        si = torch.as_tensor(
            sub_pos,
            device=h.device,
            dtype=torch.long,
        )
        ri = torch.as_tensor(
            ref_pos,
            device=h.device,
            dtype=torch.long,
        )

        pair = (
            h.index_select(0, si).mean(0)
            - h.index_select(0, ri).mean(0)
        )
        h_last = h[-1]

        obj[int(L)] = (
            pair.detach()
            .float()
            .cpu()
            .numpy()
            .astype(np.float32)
        )
        last[int(L)] = (
            h_last.detach()
            .float()
            .cpu()
            .numpy()
            .astype(np.float32)
        )

    del out, hst
    return obj, last


def fit_spatial_centroids(
    train_items: List[dict],
    obj_q: Dict[int, Dict[int, np.ndarray]],
    last_q: Dict[int, Dict[int, np.ndarray]],
    layers: Sequence[int],
):
    """
    Relation centroids use TRAIN relation labels.
    """
    obj_rel = {L: {} for L in layers}
    last_rel = {L: {} for L in layers}

    for L in layers:
        for rel in REL:
            xo = [
                obj_q[int(m["sid"])][L]
                for m in train_items
                if int(m["sid"]) in obj_q
                and m["gt"] == rel
            ]
            xl = [
                last_q[int(m["sid"])][L]
                for m in train_items
                if int(m["sid"]) in last_q
                and m["gt"] == rel
            ]

            if not xo or not xl:
                raise RuntimeError(
                    f"No TRAIN spatial states for relation={rel} L{L}"
                )

            obj_rel[L][rel] = (
                np.mean(np.stack(xo), axis=0)
                .astype(np.float32)
            )
            last_rel[L][rel] = (
                np.mean(np.stack(xl), axis=0)
                .astype(np.float32)
            )

    return obj_rel, last_rel


def fit_option_centroids(
    train_items: List[dict],
    generation_by_sid: Dict[int, dict],
    obj_q: Dict[int, Dict[int, np.ndarray]],
    last_q: Dict[int, Dict[int, np.ndarray]],
    layers: Sequence[int],
):
    """
    Option centroids are fit from the A/B/C/D option ACTUALLY generated
    by the model on TRAIN.

    This is intentionally a decision readout, not a GT-option readout.
    Unparseable TRAIN generations are omitted.
    """
    obj_opt = {L: {} for L in layers}
    last_opt = {L: {} for L in layers}

    parseable = [
        m
        for m in train_items
        if int(m["sid"]) in generation_by_sid
        and generation_by_sid[int(m["sid"])].get("pred_option")
        in LETTERS
    ]

    counts = Counter(
        generation_by_sid[int(m["sid"])]["pred_option"]
        for m in parseable
    )

    print(
        "TRAIN generated-option counts used for decision centroids:",
        dict(counts),
        flush=True,
    )

    missing = [
        a for a in LETTERS
        if counts.get(a, 0) == 0
    ]
    if missing:
        raise RuntimeError(
            "Cannot fit generated-decision centroids; "
            f"missing TRAIN generated classes: {missing}"
        )

    for L in layers:
        for opt in LETTERS:
            xo = [
                obj_q[int(m["sid"])][L]
                for m in parseable
                if generation_by_sid[int(m["sid"])]["pred_option"]
                == opt
            ]
            xl = [
                last_q[int(m["sid"])][L]
                for m in parseable
                if generation_by_sid[int(m["sid"])]["pred_option"]
                == opt
            ]

            obj_opt[L][opt] = (
                np.mean(np.stack(xo), axis=0)
                .astype(np.float32)
            )
            last_opt[L][opt] = (
                np.mean(np.stack(xl), axis=0)
                .astype(np.float32)
            )

    return obj_opt, last_opt, counts


def eval_layerwise(
    *,
    subset_name: str,
    items: List[dict],
    generation_by_sid: Dict[int, dict],
    obj_q,
    last_q,
    obj_rel_cent,
    last_rel_cent,
    obj_opt_cent,
    last_opt_cent,
    layers,
):
    """
    Spatial Readout:
        max over carriers at each layer of aggregate held-out relation accuracy.

    Option Readout:
        max over carriers at each layer of aggregate held-out generated-option accuracy.

    The max is layer-level, never per-example.
    """
    rows = []

    for L in layers:
        n_spatial = 0
        obj_rel_ok = 0
        last_rel_ok = 0

        n_option = 0
        obj_opt_ok = 0
        last_opt_ok = 0

        for m in items:
            sid = int(m["sid"])
            if (
                sid not in obj_q
                or sid not in last_q
                or sid not in generation_by_sid
            ):
                continue

            gt_rel = m["gt"]

            pred_obj_rel = nearest_centroid(
                obj_q[sid][L],
                obj_rel_cent[L],
            )
            pred_last_rel = nearest_centroid(
                last_q[sid][L],
                last_rel_cent[L],
            )

            obj_rel_ok += int(pred_obj_rel == gt_rel)
            last_rel_ok += int(pred_last_rel == gt_rel)
            n_spatial += 1

            generated_opt = generation_by_sid[sid].get("pred_option")
            if generated_opt in LETTERS:
                pred_obj_opt = nearest_centroid(
                    obj_q[sid][L],
                    obj_opt_cent[L],
                )
                pred_last_opt = nearest_centroid(
                    last_q[sid][L],
                    last_opt_cent[L],
                )

                obj_opt_ok += int(pred_obj_opt == generated_opt)
                last_opt_ok += int(pred_last_opt == generated_opt)
                n_option += 1

        if n_spatial == 0:
            raise RuntimeError(
                f"No spatial samples in subset={subset_name}"
            )
        if n_option == 0:
            raise RuntimeError(
                f"No parseable option samples in subset={subset_name}"
            )

        obj_rel_acc = obj_rel_ok / n_spatial
        last_rel_acc = last_rel_ok / n_spatial
        obj_opt_acc = obj_opt_ok / n_option
        last_opt_acc = last_opt_ok / n_option

        if obj_rel_acc >= last_rel_acc:
            spatial_acc = obj_rel_acc
            spatial_source = "object_pair"
        else:
            spatial_acc = last_rel_acc
            spatial_source = "prompt_final"

        if obj_opt_acc >= last_opt_acc:
            option_acc = obj_opt_acc
            option_source = "object_pair"
        else:
            option_acc = last_opt_acc
            option_source = "prompt_final"

        rows.append(
            {
                "subset": subset_name,
                "layer": int(L),

                "spatial_N": int(n_spatial),
                "object_pair_spatial_acc": float(obj_rel_acc),
                "prompt_final_spatial_acc": float(last_rel_acc),
                "spatial_readout_acc": float(spatial_acc),
                "spatial_source": spatial_source,

                "option_N": int(n_option),
                "object_pair_option_acc": float(obj_opt_acc),
                "prompt_final_option_acc": float(last_opt_acc),
                "option_readout_acc": float(option_acc),
                "option_source": option_source,
            }
        )

    return rows


def plot_readouts(
    rows: List[dict],
    out_png: Path,
):
    """
    Paper-facing figure:
      - no title
      - no GT wording
      - no chance line
      - direct y-axis label
      - only two legend labels
    """
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    layers = [int(r["layer"]) for r in rows]
    spatial = [
        float(r["spatial_readout_acc"])
        for r in rows
    ]
    option = [
        float(r["option_readout_acc"])
        for r in rows
    ]

    fig, ax = plt.subplots(figsize=(8.8, 4.9))

    ax.plot(
        layers,
        spatial,
        marker="o",
        linewidth=2.0,
        markersize=4.5,
        label="Spatial Readout",
    )
    ax.plot(
        layers,
        option,
        marker="o",
        linewidth=2.0,
        markersize=4.5,
        label="Option Readout",
    )

    ax.set_xlabel("Decoder Layer")
    ax.set_ylabel("Readout Accuracy")
    ax.set_ylim(0.0, 1.0)

    # Keep x-axis readable but retain layer ordering.
    if len(layers) > 18:
        ticks = layers[::2]
        if layers[-1] not in ticks:
            ticks.append(layers[-1])
        ax.set_xticks(ticks)
    else:
        ax.set_xticks(layers)

    ax.legend(frameon=False)
    fig.tight_layout()
    fig.savefig(
        out_png,
        dpi=260,
        bbox_inches="tight",
    )
    plt.close(fig)


def main():
    a = parse_args()

    random.seed(a.seed)
    np.random.seed(a.seed)
    torch.manual_seed(a.seed)

    if (
        a.device.startswith("cuda")
        and not torch.cuda.is_available()
    ):
        raise RuntimeError(
            "CUDA requested but unavailable"
        )

    outdir = Path(a.output_dir)
    if a.overwrite and outdir.exists():
        shutil.rmtree(outdir)

    if outdir.exists() and any(outdir.iterdir()):
        raise RuntimeError(
            f"Non-empty output dir: {outdir}; use --overwrite"
        )

    outdir.mkdir(
        parents=True,
        exist_ok=True,
    )
    error_path = outdir / "errors.jsonl"

    two = base.import_two_object_module()
    prompts = base.load_standard_prompts(
        Path(a.prompt_jsonl)
    )
    records, _audit = two.load_records(
        "coco_two",
        Path(a.data_root),
        None,
    )
    rec_by_sid = {
        int(r.sid): r
        for r in records
    }

    meta = []
    for r in records:
        sid = int(r.sid)
        if sid not in prompts:
            continue

        p = prompts[sid]
        gt = traj.normalize_relation(
            base,
            p["answer_raw"],
        )
        if gt not in REL:
            continue

        meta.append(
            {
                "sid": sid,
                "gt": gt,
                "subject": str(p["subject"]),
                "reference": str(p["reference"]),
            }
        )

    meta = traj.stratified_cap(
        meta,
        a.max_samples,
        a.seed,
    )
    train, test = traj.stratified_split(
        meta,
        a.train_ratio,
        a.seed,
    )
    test = traj.stratified_cap(
        test,
        a.eval_max_samples,
        a.seed + 1,
    )

    train_map = rm.assign_relation_balanced_mappings(
        train,
        a.seed + 1001,
    )
    test_map = rm.assign_relation_balanced_mappings(
        test,
        a.seed + 2003,
    )

    specs = base.merged_model_specs(two)
    spec = specs[a.model]
    cls = getattr(
        transformers,
        spec.model_class,
    )

    kw = {
        "dtype": base.resolve_dtype(
            spec.dtype_name
        ),
        "low_cpu_mem_usage": True,
        "trust_remote_code": spec.trust_remote_code,
        "device_map": {"": a.device},
    }
    if a.attn_impl != "none":
        kw["attn_implementation"] = a.attn_impl

    model = None
    processor = None

    obj_q: Dict[
        int,
        Dict[int, np.ndarray],
    ] = {}
    last_q: Dict[
        int,
        Dict[int, np.ndarray],
    ] = {}

    generation_rows: List[dict] = []

    try:
        print(
            f"Loading {spec.repo_id}",
            flush=True,
        )

        model = cls.from_pretrained(
            spec.repo_id,
            **kw,
        )
        model.eval()

        processor = AutoProcessor.from_pretrained(
            spec.repo_id,
            trust_remote_code=spec.trust_remote_code,
        )
        base.configure_processor(
            model,
            processor,
        )

        if (
            getattr(
                model,
                "generation_config",
                None,
            )
            is not None
            and model.generation_config.pad_token_id
            is None
        ):
            model.generation_config.pad_token_id = (
                model.generation_config.eos_token_id
            )

        device = torch.device(a.device)
        decoder_layers, decoder_path = (
            base.resolve_decoder_layers(model)
        )
        layers = parse_layers(
            a.layers,
            len(decoder_layers),
        )

        print("=" * 120)
        print(
            "QWEN3B + COCO: "
            "CARRIER-AGNOSTIC SPATIAL VS OPTION READOUT"
        )
        print("=" * 120)
        print(
            f"decoder={decoder_path} | "
            f"n_layers={len(decoder_layers)}"
        )
        print(f"layers={layers}")
        print(
            f"train/test={len(train)}/{len(test)}"
        )
        print(
            "Spatial Readout(l) = max("
            "relation@object-pair, "
            "relation@prompt-final)"
        )
        print(
            "Option Readout(l) = max("
            "generated-option@object-pair, "
            "generated-option@prompt-final)"
        )
        print(
            "Both maxima are layer-level held-out "
            "aggregate accuracies, not per-sample oracle choices."
        )
        print()

        # ------------------------------------------------------------
        # Capture states AND actual generated A/B/C/D option
        # for both TRAIN and TEST.
        #
        # TRAIN generations are needed so decision centroids are fit
        # from the model's own generated decision identity.
        # ------------------------------------------------------------
        for split_name, items, maps in (
            ("TRAIN", train, train_map),
            ("TEST", test, test_map),
        ):
            for m in tqdm(
                items,
                desc=f"{split_name} states+generation",
            ):
                sid = int(m["sid"])
                mp = maps[sid]

                prompt = rm.build_randmap_prompt(
                    m["subject"],
                    m["reference"],
                    mp,
                )

                real = gray = None
                rb = gb = None

                try:
                    real = rm.make_real_image(
                        rec_by_sid[sid]
                    )
                    gray = make_gray_like(
                        real,
                        a.gray_value,
                    )

                    rb = rm.make_batch(
                        processor,
                        device,
                        real,
                        prompt,
                    )
                    gb = rm.make_batch(
                        processor,
                        device,
                        gray,
                        prompt,
                    )

                    obj_r, last_r = (
                        capture_obj_and_last(
                            model=model,
                            processor=processor,
                            decoder_layers=decoder_layers,
                            batch=rb,
                            subject=m["subject"],
                            reference=m["reference"],
                            layers=layers,
                        )
                    )
                    obj_g, last_g = (
                        capture_obj_and_last(
                            model=model,
                            processor=processor,
                            decoder_layers=decoder_layers,
                            batch=gb,
                            subject=m["subject"],
                            reference=m["reference"],
                            layers=layers,
                        )
                    )

                    obj_q[sid] = {
                        L: (
                            obj_r[L]
                            - obj_g[L]
                        ).astype(np.float32)
                        for L in layers
                    }
                    last_q[sid] = {
                        L: (
                            last_r[L]
                            - last_g[L]
                        ).astype(np.float32)
                        for L in layers
                    }

                    pred, text, parse_mode, _ = (
                        rm.generate_one(
                            model=model,
                            processor=processor,
                            decoder_layers=decoder_layers,
                            batch=rb,
                            mapping=mp,
                            max_new_tokens=a.max_new_tokens,
                        )
                    )

                    correct_option = mp[m["gt"]]

                    generation_rows.append(
                        {
                            "split": split_name.lower(),
                            "sid": sid,
                            "relation": m["gt"],
                            "pred_option": pred,
                            "parseable_option": pred in LETTERS,
                            "generation_correct": (
                                pred == correct_option
                            ),
                            "text": text,
                            "parse_mode": parse_mode,
                            "mapping": rm.mapping_string(mp),
                        }
                    )

                except Exception as exc:
                    err = {
                        "phase": split_name.lower(),
                        "sid": sid,
                        "error": (
                            f"{type(exc).__name__}: {exc}"
                        ),
                        "traceback": traceback.format_exc(),
                    }
                    with error_path.open(
                        "a",
                        encoding="utf-8",
                    ) as f:
                        f.write(
                            json.dumps(
                                err,
                                ensure_ascii=False,
                            )
                            + "\n"
                        )
                    raise

                finally:
                    for im in (real, gray):
                        if im is not None:
                            with contextlib.suppress(
                                Exception
                            ):
                                im.close()

                    del rb, gb
                    gc.collect()

        write_csv(
            outdir / "generation.csv",
            generation_rows,
        )

        generation_by_sid = {
            int(r["sid"]): r
            for r in generation_rows
        }

        train = [
            m
            for m in train
            if (
                int(m["sid"]) in obj_q
                and int(m["sid"]) in last_q
                and int(m["sid"]) in generation_by_sid
            )
        ]

        test = [
            m
            for m in test
            if (
                int(m["sid"]) in obj_q
                and int(m["sid"]) in last_q
                and int(m["sid"]) in generation_by_sid
            )
        ]

        correct_test = [
            m
            for m in test
            if generation_by_sid[
                int(m["sid"])
            ]["generation_correct"]
        ]

        train_parseable = [
            m
            for m in train
            if generation_by_sid[
                int(m["sid"])
            ]["pred_option"]
            in LETTERS
        ]
        test_parseable = [
            m
            for m in test
            if generation_by_sid[
                int(m["sid"])
            ]["pred_option"]
            in LETTERS
        ]

        print(
            "\nGeneration summary:",
            flush=True,
        )
        print(
            f"  TRAIN parseable option: "
            f"{len(train_parseable)}/{len(train)}",
            flush=True,
        )
        print(
            f"  TEST parseable option: "
            f"{len(test_parseable)}/{len(test)}",
            flush=True,
        )
        print(
            f"  TEST correct: "
            f"{len(correct_test)}/{len(test)} "
            f"({len(correct_test) / max(len(test), 1):.4f})",
            flush=True,
        )

        # ------------------------------------------------------------
        # TRAIN-only readout fitting.
        # ------------------------------------------------------------
        obj_rel_cent, last_rel_cent = (
            fit_spatial_centroids(
                train,
                obj_q,
                last_q,
                layers,
            )
        )

        (
            obj_opt_cent,
            last_opt_cent,
            train_option_counts,
        ) = fit_option_centroids(
            train,
            generation_by_sid,
            obj_q,
            last_q,
            layers,
        )

        # ------------------------------------------------------------
        # Held-out ALL and CORRECT-only evaluation.
        # ------------------------------------------------------------
        all_rows = eval_layerwise(
            subset_name="all",
            items=test,
            generation_by_sid=generation_by_sid,
            obj_q=obj_q,
            last_q=last_q,
            obj_rel_cent=obj_rel_cent,
            last_rel_cent=last_rel_cent,
            obj_opt_cent=obj_opt_cent,
            last_opt_cent=last_opt_cent,
            layers=layers,
        )

        correct_rows = eval_layerwise(
            subset_name="correct",
            items=correct_test,
            generation_by_sid=generation_by_sid,
            obj_q=obj_q,
            last_q=last_q,
            obj_rel_cent=obj_rel_cent,
            last_rel_cent=last_rel_cent,
            obj_opt_cent=obj_opt_cent,
            last_opt_cent=last_opt_cent,
            layers=layers,
        )

        write_csv(
            outdir / "layerwise_readout_all.csv",
            all_rows,
        )
        write_csv(
            outdir / "layerwise_readout_correct.csv",
            correct_rows,
        )

        plot_readouts(
            all_rows,
            outdir / "spatial_option_readout_all.png",
        )
        plot_readouts(
            correct_rows,
            outdir / "spatial_option_readout_correct.png",
        )

        print("\n" + "=" * 128)
        print("ALL HELD-OUT TEST SAMPLES")
        print("=" * 128)
        for r in all_rows:
            print(
                f"L{int(r['layer']):02d} | "
                f"Spatial={r['spatial_readout_acc']:.4f}"
                f"[{r['spatial_source']}] "
                f"(obj={r['object_pair_spatial_acc']:.4f}, "
                f"last={r['prompt_final_spatial_acc']:.4f}) | "
                f"Option={r['option_readout_acc']:.4f}"
                f"[{r['option_source']}] "
                f"(obj={r['object_pair_option_acc']:.4f}, "
                f"last={r['prompt_final_option_acc']:.4f}) | "
                f"Nopt={int(r['option_N'])}"
            )

        print("\n" + "=" * 128)
        print("CORRECT TEST SAMPLES ONLY")
        print("=" * 128)
        for r in correct_rows:
            print(
                f"L{int(r['layer']):02d} | "
                f"Spatial={r['spatial_readout_acc']:.4f}"
                f"[{r['spatial_source']}] "
                f"(obj={r['object_pair_spatial_acc']:.4f}, "
                f"last={r['prompt_final_spatial_acc']:.4f}) | "
                f"Option={r['option_readout_acc']:.4f}"
                f"[{r['option_source']}] "
                f"(obj={r['object_pair_option_acc']:.4f}, "
                f"last={r['prompt_final_option_acc']:.4f})"
            )

        metadata = {
            "model_alias": a.model,
            "repo_id": spec.repo_id,
            "decoder_path": decoder_path,
            "n_decoder_layers": len(decoder_layers),
            "layers": list(map(int, layers)),
            "seed": int(a.seed),
            "train_ratio": float(a.train_ratio),

            "N_train": len(train),
            "N_test": len(test),
            "N_test_correct": len(correct_test),
            "N_train_option_parseable": len(train_parseable),
            "N_test_option_parseable": len(test_parseable),

            "spatial_readout": (
                "per-layer max of held-out relation accuracy "
                "from object-pair Real-Gray and prompt-final Real-Gray carriers"
            ),
            "option_readout": (
                "per-layer max of held-out generated A/B/C/D option accuracy "
                "from object-pair Real-Gray and prompt-final Real-Gray carriers"
            ),
            "max_rule": (
                "layer-level aggregate accuracy max; never per-example oracle"
            ),
            "option_centroid_labels": (
                "A/B/C/D actually generated by the model on TRAIN"
            ),
            "same_question_constraint": (
                "spatial and option readouts use the same sample, image, randomized "
                "A/B/C/D prompt, forward states, and train/test split"
            ),
            "train_generated_option_counts": {
                str(k): int(v)
                for k, v in train_option_counts.items()
            },

            "figure_style": {
                "x_label": "Decoder Layer",
                "y_label": "Readout Accuracy",
                "legend": [
                    "Spatial Readout",
                    "Option Readout",
                ],
                "chance_line": False,
                "title": False,
            },
        }

        (
            outdir / "metadata.json"
        ).write_text(
            json.dumps(
                metadata,
                indent=2,
                ensure_ascii=False,
            ),
            encoding="utf-8",
        )

        print("\nSaved:")
        for name in (
            "spatial_option_readout_all.png",
            "spatial_option_readout_correct.png",
            "layerwise_readout_all.csv",
            "layerwise_readout_correct.csv",
            "generation.csv",
            "metadata.json",
        ):
            print(
                " ",
                outdir / name,
            )

    finally:
        if model is not None:
            del model
        if processor is not None:
            del processor

        gc.collect()

        if torch.cuda.is_available():
            torch.cuda.empty_cache()


if __name__ == "__main__":
    main()
