#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Qwen2.5-VL-3B + COCO random-map layer-wise readout.

This version intentionally uses the SAME full sample set to define and evaluate
the readout directions. It is a descriptive in-sample representation analysis,
not a held-out probe-generalization experiment.

At each decoder layer and for each carrier separately:

Spatial directions
------------------
For r in {left, right, above, below}:

    mu_r,l = mean_i q_i,l  over all samples with relation r
    mu_l   = (1/4) sum_r mu_r,l
    d_r,l  = unit(mu_r,l - mu_l)

Prediction:

    r_hat_i,l = argmax_r cos(q_i,l - mu_l, d_r,l)

Option directions
-----------------
For c in {A, B, C, D}, using the option ACTUALLY GENERATED by the model:

    nu_c,l = mean_i q_i,l  over all samples with generated option c
    nu_l   = (1/4) sum_c nu_c,l
    e_c,l  = unit(nu_c,l - nu_l)

Prediction:

    c_hat_i,l = argmax_c cos(q_i,l - nu_l, e_c,l)

Two candidate carriers are evaluated independently:

    object-pair:
      q_obj,l =
        (h_real[sub] - h_real[ref])
        - (h_gray[sub] - h_gray[ref])

    prompt-final:
      q_last,l =
        h_real[last] - h_gray[last]

The plotted curves are layer-level maxima:

    Spatial Readout(l)
      = max(
          relation accuracy from q_obj,l,
          relation accuracy from q_last,l
        )

    Option Readout(l)
      = max(
          generated-option accuracy from q_obj,l,
          generated-option accuracy from q_last,l
        )

The max is over aggregate layer-level accuracy, never per-example oracle choice.

Both readouts use:
  - the same samples,
  - the same image,
  - the same randomized relation -> A/B/C/D question,
  - the same forward states.

Main output:
    spatial_option_readout_insample.png

Additional audit outputs:
    layerwise_readout_insample.csv
    generation.csv
    direction_metadata.json
    metadata.json

Run from the AdaptVis llava16 repository root.

Full run
--------
CUDA_VISIBLE_DEVICES=0 PYTHONUNBUFFERED=1 \
python -u qwen3b_coco_spatial_option_direction_insample_v3.py \
  --max-samples 0 \
  --output-dir output/qwen3b_coco_spatial_option_direction_insample_v3 \
  --overwrite

Quick run
---------
CUDA_VISIBLE_DEVICES=0 PYTHONUNBUFFERED=1 \
python -u qwen3b_coco_spatial_option_direction_insample_v3.py \
  --max-samples 160 \
  --output-dir output/qwen3b_coco_spatial_option_direction_insample_quick \
  --overwrite
"""

from __future__ import annotations

import argparse
import contextlib
import csv
import gc
import json
import random
import shutil
import traceback
from collections import Counter
from pathlib import Path
from typing import Dict, List, Mapping, Sequence, Tuple

import numpy as np
import torch
import transformers
from transformers import AutoProcessor
from tqdm import tqdm

import eval_qwen_coco_randmap_late_spatial_deconfound_quick as rm
import eval_multimodel_targetselected_head_spatial_control_genflip_trust_v6 as v6

base = rm.base
traj = rm.traj
REL = tuple(rm.REL)
LETTERS = tuple(rm.LETTERS)
EPS = 1e-12


def parse_args():
    p = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    p.add_argument("--data-root", default="data")
    p.add_argument(
        "--prompt-jsonl",
        default="prompts/COCO_QA_two_obj_with_answer_four_options.jsonl",
    )
    p.add_argument("--model", default="qwen-3b", choices=["qwen-3b"])
    p.add_argument(
        "--layers",
        default="all",
        help="all = every decoder block; otherwise comma list such as 20,21,22,23,24,25,26,27",
    )
    p.add_argument("--seed", type=int, default=17)
    p.add_argument(
        "--max-samples",
        type=int,
        default=0,
        help="0 = all available COCO-two samples",
    )
    p.add_argument("--gray-value", type=int, default=128)
    p.add_argument("--max-new-tokens", type=int, default=4)
    p.add_argument("--device", default="cuda:0")
    p.add_argument(
        "--attn-impl",
        default="eager",
        choices=["eager", "sdpa", "flash_attention_2", "none"],
    )
    p.add_argument("--output-dir", required=True)
    p.add_argument("--overwrite", action="store_true")
    return p.parse_args()


def write_csv(path: Path, rows: List[dict]):
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return

    fields = []
    seen = set()
    for row in rows:
        for k in row:
            if k not in seen:
                fields.append(k)
                seen.add(k)

    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(rows)


def parse_layers(text: str, n_layers: int) -> List[int]:
    if text.strip().lower() == "all":
        return list(range(n_layers))

    out = sorted(
        {
            int(x.strip().upper().replace("L", ""))
            for x in text.split(",")
            if x.strip()
        }
    )
    bad = [x for x in out if not (0 <= x < n_layers)]
    if bad:
        raise ValueError(
            f"Invalid layers {bad}; model has L0-L{n_layers - 1}"
        )
    return out


def unit_np(x: np.ndarray) -> np.ndarray:
    x = np.asarray(x, dtype=np.float64)
    n = float(np.linalg.norm(x))
    if n <= EPS:
        return np.zeros_like(x, dtype=np.float32)
    return (x / n).astype(np.float32)


def cosine_np(a: np.ndarray, b: np.ndarray) -> float:
    a = np.asarray(a, dtype=np.float64).reshape(-1)
    b = np.asarray(b, dtype=np.float64).reshape(-1)
    den = float(np.linalg.norm(a) * np.linalg.norm(b))
    if den <= EPS:
        return float("-inf")
    return float(np.dot(a, b) / den)


def make_gray_like(image, value: int):
    from PIL import Image
    v = int(max(0, min(255, value)))
    return Image.new("RGB", image.size, (v, v, v))


def capture_obj_and_last(
    *,
    model,
    processor,
    decoder_layers: Sequence,
    batch: Dict[str, torch.Tensor],
    subject: str,
    reference: str,
    layers: Sequence[int],
) -> Tuple[Dict[int, np.ndarray], Dict[int, np.ndarray]]:
    """
    One no-grad multimodal forward.

    Returns decoder-block output states:
      obj[L]  = mean(h_subject) - mean(h_reference)
      last[L] = h_prompt-final
    """
    ids = [int(x) for x in batch["input_ids"][0].detach().cpu().tolist()]

    sub_raw = v6.hs.headprobe.locate_phrase_positions(
        processor.tokenizer, ids, subject
    )
    ref_raw = v6.hs.headprobe.locate_phrase_positions(
        processor.tokenizer, ids, reference
    )

    with torch.inference_mode():
        out = model(
            **batch,
            output_hidden_states=True,
            output_attentions=False,
            use_cache=False,
            return_dict=True,
        )

    hst = v6.extract_hidden_states(out)
    if len(hst) < len(decoder_layers) + 1:
        raise RuntimeError(
            f"hidden_states length={len(hst)} "
            f"but decoder layers={len(decoder_layers)}"
        )

    merged_len = int(hst[0].shape[1])

    sub_pos, _ = v6.recv.map_text_positions_to_decoder(
        model=model,
        processor=processor,
        input_ids=ids,
        raw_positions=sub_raw,
        merged_length=merged_len,
    )
    ref_pos, _ = v6.recv.map_text_positions_to_decoder(
        model=model,
        processor=processor,
        input_ids=ids,
        raw_positions=ref_raw,
        merged_length=merged_len,
    )

    if not sub_pos or not ref_pos:
        raise RuntimeError(
            f"Could not map subject/reference positions: "
            f"subject={subject!r}, reference={reference!r}"
        )

    obj = {}
    last = {}

    for L in layers:
        h = hst[int(L) + 1][0]

        si = torch.as_tensor(
            sub_pos, device=h.device, dtype=torch.long
        )
        ri = torch.as_tensor(
            ref_pos, device=h.device, dtype=torch.long
        )

        pair = (
            h.index_select(0, si).mean(0)
            - h.index_select(0, ri).mean(0)
        )
        h_last = h[-1]

        obj[int(L)] = (
            pair.detach()
            .float()
            .cpu()
            .numpy()
            .astype(np.float32)
        )
        last[int(L)] = (
            h_last.detach()
            .float()
            .cpu()
            .numpy()
            .astype(np.float32)
        )

    del out, hst
    return obj, last


def fit_centered_directions(
    *,
    items: List[dict],
    labels_by_sid: Mapping[int, str],
    states: Dict[int, Dict[int, np.ndarray]],
    layers: Sequence[int],
    classes: Sequence[str],
):
    """
    Full-dataset, per-layer centered class directions.

    Every sample assigned to a valid class contributes to the class mean.
    The same samples are later evaluated.

        mu_c,l = mean(q_i,l | y_i=c)
        mu_l   = mean_c mu_c,l
        d_c,l  = unit(mu_c,l - mu_l)

    The center is the unweighted mean over class means, matching the
    four-relation geometry used elsewhere in the project.
    """
    centers = {}
    directions = {}
    class_means = {}
    counts = Counter()

    valid_items = [
        m
        for m in items
        if int(m["sid"]) in states
        and int(m["sid"]) in labels_by_sid
        and labels_by_sid[int(m["sid"])] in classes
    ]

    for m in valid_items:
        counts[labels_by_sid[int(m["sid"])]] += 1

    missing = [c for c in classes if counts[c] == 0]
    if missing:
        raise RuntimeError(
            f"Cannot construct directions; missing classes: {missing}"
        )

    for L in layers:
        means = {}

        for c in classes:
            xs = [
                states[int(m["sid"])][L]
                for m in valid_items
                if labels_by_sid[int(m["sid"])] == c
            ]
            means[c] = (
                np.mean(np.stack(xs), axis=0)
                .astype(np.float32)
            )

        center = (
            np.mean(
                np.stack([means[c] for c in classes]),
                axis=0,
            )
            .astype(np.float32)
        )

        dirs = {
            c: unit_np(means[c] - center)
            for c in classes
        }

        centers[int(L)] = center
        directions[int(L)] = dirs
        class_means[int(L)] = means

    return centers, directions, class_means, counts


def predict_direction(
    x: np.ndarray,
    center: np.ndarray,
    directions: Mapping[str, np.ndarray],
    classes: Sequence[str],
) -> str:
    z = np.asarray(x, dtype=np.float32) - np.asarray(
        center, dtype=np.float32
    )

    scores = [
        cosine_np(z, directions[c])
        for c in classes
    ]
    scores = [
        -1e30 if not np.isfinite(s) else s
        for s in scores
    ]
    return classes[int(np.argmax(scores))]


def evaluate_direction_readout(
    *,
    items: List[dict],
    labels_by_sid: Mapping[int, str],
    states: Dict[int, Dict[int, np.ndarray]],
    centers,
    directions,
    layers,
    classes,
):
    rows = {}

    valid_items = [
        m
        for m in items
        if int(m["sid"]) in states
        and int(m["sid"]) in labels_by_sid
        and labels_by_sid[int(m["sid"])] in classes
    ]

    for L in layers:
        correct = 0
        n = 0

        per_class_n = Counter()
        per_class_correct = Counter()

        for m in valid_items:
            sid = int(m["sid"])
            label = labels_by_sid[sid]

            pred = predict_direction(
                states[sid][L],
                centers[L],
                directions[L],
                classes,
            )

            ok = pred == label
            correct += int(ok)
            n += 1
            per_class_n[label] += 1
            per_class_correct[label] += int(ok)

        if n == 0:
            raise RuntimeError(f"No evaluable samples at L{L}")

        rows[L] = {
            "N": int(n),
            "accuracy": float(correct / n),
        }

        for c in classes:
            rows[L][f"N_{c}"] = int(per_class_n[c])
            rows[L][f"acc_{c}"] = (
                float(per_class_correct[c] / per_class_n[c])
                if per_class_n[c] > 0
                else float("nan")
            )

    return rows


def plot_readouts(rows: List[dict], out_png: Path):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    layers = [int(r["layer"]) for r in rows]
    spatial = [float(r["spatial_readout_acc"]) for r in rows]
    option = [float(r["option_readout_acc"]) for r in rows]

    fig, ax = plt.subplots(figsize=(8.8, 4.9))

    ax.plot(
        layers,
        spatial,
        marker="o",
        linewidth=2.0,
        markersize=4.5,
        label="Spatial Readout",
    )
    ax.plot(
        layers,
        option,
        marker="o",
        linewidth=2.0,
        markersize=4.5,
        label="Option Readout",
    )

    ax.set_xlabel("Decoder Layer")
    ax.set_ylabel("Readout Accuracy")
    ax.set_ylim(0.0, 1.0)

    if len(layers) > 18:
        ticks = layers[::2]
        if layers[-1] not in ticks:
            ticks.append(layers[-1])
        ax.set_xticks(ticks)
    else:
        ax.set_xticks(layers)

    ax.legend(frameon=False)
    fig.tight_layout()
    fig.savefig(out_png, dpi=260, bbox_inches="tight")
    plt.close(fig)


def main():
    a = parse_args()

    random.seed(a.seed)
    np.random.seed(a.seed)
    torch.manual_seed(a.seed)

    if a.device.startswith("cuda") and not torch.cuda.is_available():
        raise RuntimeError("CUDA requested but unavailable")

    outdir = Path(a.output_dir)
    if a.overwrite and outdir.exists():
        shutil.rmtree(outdir)

    if outdir.exists() and any(outdir.iterdir()):
        raise RuntimeError(f"Non-empty output dir: {outdir}; use --overwrite")

    outdir.mkdir(parents=True, exist_ok=True)
    error_path = outdir / "errors.jsonl"

    two = base.import_two_object_module()
    prompts = base.load_standard_prompts(Path(a.prompt_jsonl))
    records, _audit = two.load_records(
        "coco_two",
        Path(a.data_root),
        None,
    )
    rec_by_sid = {int(r.sid): r for r in records}

    items = []
    for r in records:
        sid = int(r.sid)
        if sid not in prompts:
            continue

        p = prompts[sid]
        gt = traj.normalize_relation(base, p["answer_raw"])
        if gt not in REL:
            continue

        items.append(
            {
                "sid": sid,
                "gt": gt,
                "subject": str(p["subject"]),
                "reference": str(p["reference"]),
            }
        )

    # One sample pool only. No train/test split.
    items = traj.stratified_cap(
        items,
        a.max_samples,
        a.seed,
    )

    # One deterministic balanced random mapping over the full sample pool.
    mappings = rm.assign_relation_balanced_mappings(
        items,
        a.seed + 2003,
    )

    specs = base.merged_model_specs(two)
    spec = specs[a.model]
    cls = getattr(transformers, spec.model_class)

    kw = {
        "dtype": base.resolve_dtype(spec.dtype_name),
        "low_cpu_mem_usage": True,
        "trust_remote_code": spec.trust_remote_code,
        "device_map": {"": a.device},
    }
    if a.attn_impl != "none":
        kw["attn_implementation"] = a.attn_impl

    model = None
    processor = None

    obj_q: Dict[int, Dict[int, np.ndarray]] = {}
    last_q: Dict[int, Dict[int, np.ndarray]] = {}
    generation_rows: List[dict] = []

    try:
        print(f"Loading {spec.repo_id}", flush=True)

        model = cls.from_pretrained(spec.repo_id, **kw)
        model.eval()

        processor = AutoProcessor.from_pretrained(
            spec.repo_id,
            trust_remote_code=spec.trust_remote_code,
        )
        base.configure_processor(model, processor)

        if (
            getattr(model, "generation_config", None) is not None
            and model.generation_config.pad_token_id is None
        ):
            model.generation_config.pad_token_id = (
                model.generation_config.eos_token_id
            )

        device = torch.device(a.device)
        decoder_layers, decoder_path = base.resolve_decoder_layers(model)
        layers = parse_layers(a.layers, len(decoder_layers))

        print("=" * 120)
        print("QWEN3B + COCO: FULL-DATA PER-LAYER DIRECTION READOUT")
        print("=" * 120)
        print(f"decoder={decoder_path} | n_layers={len(decoder_layers)}")
        print(f"layers={layers}")
        print(f"N={len(items)}")
        print("No train/test split.")
        print(
            "Each layer constructs its own centered four-class directions "
            "from the complete sample pool and evaluates the same pool."
        )
        print()

        # ------------------------------------------------------------------
        # Capture every sample once.
        # ------------------------------------------------------------------
        for m in tqdm(items, desc="all samples states+generation"):
            sid = int(m["sid"])
            mp = mappings[sid]

            prompt = rm.build_randmap_prompt(
                m["subject"],
                m["reference"],
                mp,
            )

            real = gray = None
            rb = gb = None

            try:
                real = rm.make_real_image(rec_by_sid[sid])
                gray = make_gray_like(real, a.gray_value)

                rb = rm.make_batch(
                    processor,
                    device,
                    real,
                    prompt,
                )
                gb = rm.make_batch(
                    processor,
                    device,
                    gray,
                    prompt,
                )

                obj_r, last_r = capture_obj_and_last(
                    model=model,
                    processor=processor,
                    decoder_layers=decoder_layers,
                    batch=rb,
                    subject=m["subject"],
                    reference=m["reference"],
                    layers=layers,
                )
                obj_g, last_g = capture_obj_and_last(
                    model=model,
                    processor=processor,
                    decoder_layers=decoder_layers,
                    batch=gb,
                    subject=m["subject"],
                    reference=m["reference"],
                    layers=layers,
                )

                obj_q[sid] = {
                    L: (obj_r[L] - obj_g[L]).astype(np.float32)
                    for L in layers
                }
                last_q[sid] = {
                    L: (last_r[L] - last_g[L]).astype(np.float32)
                    for L in layers
                }

                pred, text, parse_mode, _ = rm.generate_one(
                    model=model,
                    processor=processor,
                    decoder_layers=decoder_layers,
                    batch=rb,
                    mapping=mp,
                    max_new_tokens=a.max_new_tokens,
                )

                correct_option = mp[m["gt"]]

                generation_rows.append(
                    {
                        "sid": sid,
                        "relation": m["gt"],
                        "pred_option": pred,
                        "parseable_option": pred in LETTERS,
                        "generation_correct": pred == correct_option,
                        "text": text,
                        "parse_mode": parse_mode,
                        "mapping": rm.mapping_string(mp),
                    }
                )

            except Exception as exc:
                err = {
                    "sid": sid,
                    "error": f"{type(exc).__name__}: {exc}",
                    "traceback": traceback.format_exc(),
                }
                with error_path.open("a", encoding="utf-8") as f:
                    f.write(json.dumps(err, ensure_ascii=False) + "\n")
                raise

            finally:
                for im in (real, gray):
                    if im is not None:
                        with contextlib.suppress(Exception):
                            im.close()
                del rb, gb
                gc.collect()

        write_csv(outdir / "generation.csv", generation_rows)

        generation_by_sid = {
            int(r["sid"]): r
            for r in generation_rows
        }

        items = [
            m
            for m in items
            if int(m["sid"]) in obj_q
            and int(m["sid"]) in last_q
            and int(m["sid"]) in generation_by_sid
        ]

        spatial_labels = {
            int(m["sid"]): str(m["gt"])
            for m in items
        }

        option_labels = {
            int(m["sid"]): str(
                generation_by_sid[int(m["sid"])]["pred_option"]
            )
            for m in items
            if generation_by_sid[int(m["sid"])]["pred_option"] in LETTERS
        }

        print(
            "Spatial class counts:",
            dict(Counter(spatial_labels.values())),
            flush=True,
        )
        print(
            "Generated option counts:",
            dict(Counter(option_labels.values())),
            flush=True,
        )

        # ------------------------------------------------------------------
        # Fit per-layer FULL-DATA directions separately for each carrier.
        # ------------------------------------------------------------------
        (
            obj_spatial_center,
            obj_spatial_dirs,
            obj_spatial_means,
            spatial_counts,
        ) = fit_centered_directions(
            items=items,
            labels_by_sid=spatial_labels,
            states=obj_q,
            layers=layers,
            classes=REL,
        )

        (
            last_spatial_center,
            last_spatial_dirs,
            last_spatial_means,
            _,
        ) = fit_centered_directions(
            items=items,
            labels_by_sid=spatial_labels,
            states=last_q,
            layers=layers,
            classes=REL,
        )

        (
            obj_option_center,
            obj_option_dirs,
            obj_option_means,
            option_counts,
        ) = fit_centered_directions(
            items=items,
            labels_by_sid=option_labels,
            states=obj_q,
            layers=layers,
            classes=LETTERS,
        )

        (
            last_option_center,
            last_option_dirs,
            last_option_means,
            _,
        ) = fit_centered_directions(
            items=items,
            labels_by_sid=option_labels,
            states=last_q,
            layers=layers,
            classes=LETTERS,
        )

        # ------------------------------------------------------------------
        # Evaluate the SAME full sample pool.
        # ------------------------------------------------------------------
        obj_spatial_eval = evaluate_direction_readout(
            items=items,
            labels_by_sid=spatial_labels,
            states=obj_q,
            centers=obj_spatial_center,
            directions=obj_spatial_dirs,
            layers=layers,
            classes=REL,
        )

        last_spatial_eval = evaluate_direction_readout(
            items=items,
            labels_by_sid=spatial_labels,
            states=last_q,
            centers=last_spatial_center,
            directions=last_spatial_dirs,
            layers=layers,
            classes=REL,
        )

        obj_option_eval = evaluate_direction_readout(
            items=items,
            labels_by_sid=option_labels,
            states=obj_q,
            centers=obj_option_center,
            directions=obj_option_dirs,
            layers=layers,
            classes=LETTERS,
        )

        last_option_eval = evaluate_direction_readout(
            items=items,
            labels_by_sid=option_labels,
            states=last_q,
            centers=last_option_center,
            directions=last_option_dirs,
            layers=layers,
            classes=LETTERS,
        )

        rows = []

        for L in layers:
            obj_s = float(obj_spatial_eval[L]["accuracy"])
            last_s = float(last_spatial_eval[L]["accuracy"])
            obj_o = float(obj_option_eval[L]["accuracy"])
            last_o = float(last_option_eval[L]["accuracy"])

            if obj_s >= last_s:
                spatial_acc = obj_s
                spatial_source = "object_pair"
            else:
                spatial_acc = last_s
                spatial_source = "prompt_final"

            if obj_o >= last_o:
                option_acc = obj_o
                option_source = "object_pair"
            else:
                option_acc = last_o
                option_source = "prompt_final"

            row = {
                "layer": int(L),
                "spatial_N": int(obj_spatial_eval[L]["N"]),
                "object_pair_spatial_acc": obj_s,
                "prompt_final_spatial_acc": last_s,
                "spatial_readout_acc": spatial_acc,
                "spatial_source": spatial_source,

                "option_N": int(obj_option_eval[L]["N"]),
                "object_pair_option_acc": obj_o,
                "prompt_final_option_acc": last_o,
                "option_readout_acc": option_acc,
                "option_source": option_source,
            }

            rows.append(row)

        write_csv(
            outdir / "layerwise_readout_insample.csv",
            rows,
        )

        plot_readouts(
            rows,
            outdir / "spatial_option_readout_insample.png",
        )

        # Audit metadata for exact direction definition.
        direction_metadata = {
            "spatial_classes": list(REL),
            "option_classes": list(LETTERS),
            "spatial_class_counts": {
                str(k): int(v)
                for k, v in spatial_counts.items()
            },
            "option_class_counts": {
                str(k): int(v)
                for k, v in option_counts.items()
            },
            "direction_definition": (
                "For each layer and carrier: class mean minus unweighted "
                "mean of the four class means, then L2 normalize."
            ),
            "evaluation_definition": (
                "Cosine between centered sample state and each layer-specific "
                "class direction; same full sample pool used to define and evaluate directions."
            ),
            "carrier_max_definition": (
                "Layer-level max of aggregate accuracy across object-pair "
                "and prompt-final carriers; never per-example max."
            ),
        }

        (
            outdir / "direction_metadata.json"
        ).write_text(
            json.dumps(
                direction_metadata,
                indent=2,
                ensure_ascii=False,
            ),
            encoding="utf-8",
        )

        metadata = {
            "model_alias": a.model,
            "repo_id": spec.repo_id,
            "decoder_path": decoder_path,
            "n_decoder_layers": len(decoder_layers),
            "layers": list(map(int, layers)),
            "seed": int(a.seed),
            "N_total": len(items),
            "protocol": "full-data in-sample centered-direction readout",
            "train_test_split": False,
            "same_samples_define_and_evaluate_directions": True,
            "spatial_label": "left/right/above/below relation",
            "option_label": "A/B/C/D actually generated by the model",
            "object_pair_state": (
                "q_obj=(h_real_sub-h_real_ref)"
                "-(h_gray_sub-h_gray_ref)"
            ),
            "prompt_final_state": (
                "q_last=h_real_last-h_gray_last"
            ),
            "figure": {
                "x_label": "Decoder Layer",
                "y_label": "Readout Accuracy",
                "legend": [
                    "Spatial Readout",
                    "Option Readout",
                ],
                "chance_line": False,
                "title": False,
            },
        }

        (
            outdir / "metadata.json"
        ).write_text(
            json.dumps(
                metadata,
                indent=2,
                ensure_ascii=False,
            ),
            encoding="utf-8",
        )

        print("\n" + "=" * 120)
        print("FULL-DATA IN-SAMPLE DIRECTION READOUT")
        print("=" * 120)

        for r in rows:
            print(
                f"L{int(r['layer']):02d} | "
                f"Spatial={r['spatial_readout_acc']:.4f}"
                f"[{r['spatial_source']}] "
                f"(obj={r['object_pair_spatial_acc']:.4f}, "
                f"last={r['prompt_final_spatial_acc']:.4f}) | "
                f"Option={r['option_readout_acc']:.4f}"
                f"[{r['option_source']}] "
                f"(obj={r['object_pair_option_acc']:.4f}, "
                f"last={r['prompt_final_option_acc']:.4f})"
            )

        print("\nSaved:")
        for name in (
            "spatial_option_readout_insample.png",
            "layerwise_readout_insample.csv",
            "generation.csv",
            "direction_metadata.json",
            "metadata.json",
        ):
            print(" ", outdir / name)

    finally:
        if model is not None:
            del model
        if processor is not None:
            del processor

        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()


if __name__ == "__main__":
    main()
